/*
 * g1_imu.h -- consolidated declarations for the `sensors/imu' module.
 *
 * GENERATED by recon/refactor/transforms/t03_module_structure.py,
 * sub-batch B.  Do not edit: regenerate the stage.
 *
 * Every declaration below appeared in two or more translation units of
 * this module, and every occurrence designated the SAME C TYPE.  The
 * only differences folded are whitespace, `unsigned' vs `unsigned int'
 * (C11 6.7.2) and parameter names (C11 6.7.6.3) -- none of which is
 * part of a type, so no declaration reaching the compiler changed.
 *
 * Hoisting is REFUSED for any symbol whose declarations disagree about
 * a type anywhere in this module.  Such a disagreement is a candidate
 * reconstruction defect and is reported in DEFECTS.json rather than
 * resolved by this transformer: picking a winner would be inventing
 * evidence about a shipped ABI.
 */
#ifndef G1_MODULE_IMU_H
#define G1_MODULE_IMU_H

/* A header must be self-contained: it is included by files that did
 * not previously need <stdint.h>, and a hoisted `int64_t' or
 * `uint8_t *' declaration would otherwise fail to compile in exactly
 * those files.  Both are type-only and emit no code. */
#include <stdint.h>
#include <stddef.h>

extern int float_is_nan(float);
extern void quaternion_to_euler(unsigned long);

#endif /* G1_MODULE_IMU_H */
