/*
 * Call-cohesive translation unit for the `ble' module.
 *
 * GENERATED by recon/refactor/transforms/t09_call_cohesion.py.  Do
 * not edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 2 translation units below were grouped because they CALL ONE
 * ANOTHER, not because they were adjacent in the generated source
 * list.  Each member's text is reproduced VERBATIM.  Every member was
 * checked pairwise against every other member already in this unit by
 * stage 04's seven refusal rules, unchanged: no symbol is declared
 * here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct
 * tag or enum constant of one member is visible to a member that
 * names it.
 *
 * members, in generated-source-list order:
 *   g1_ble_07.c
 *   g1_ble_08.c
 *
 * call edges inside this unit (caller -> callee): 1
 *   g1_ble_08.c -> g1_ble_07.c
 */

/* File-scope forward declarations for every struct/union tag this
 * unit names.  Without them a tag whose only appearance in a member
 * is inside a parameter list has PARAMETER-LIST scope, so two
 * textually IDENTICAL declarations in two members declare two
 * different incomplete types and the second is a conflicting
 * redeclaration (C11 6.2.1p7).  Incomplete-type forward
 * declarations emit no code. */
struct bt_ad;
struct bt_data_record;
struct log_record;
/* ================================================================ */
/* member unit: g1_ble_07.c */
/* ================================================================ */
/*
 * Cohesive translation unit for the `ble' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 3 functions below were 3 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   hci_set_ad.c
 *   ble_conn_addr_and_params_valid.c
 *   ble_conn_addr_resolve_or_create.c
 */

/* File-scope forward declarations for every struct/union tag this
 * unit names.  Without them a tag whose only appearance in a member
 * is inside a parameter list has PARAMETER-LIST scope, so two
 * textually IDENTICAL declarations in two members declare two
 * different incomplete types and the second is a conflicting
 * redeclaration (C11 6.2.1p7).  Incomplete-type forward
 * declarations emit no code. */
struct bt_ad;
struct bt_data_record;
struct log_record;
/* ---- hci_set_ad.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_00055534 @ 0x00055534
 * public-name: hci_set_ad
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   z_log_msg_runtime_create                 <= FUN_0004d944 @ 0x0004d944
 *   bt_hci_cmd_send_sync                     <= FUN_00053d70 @ 0x00053d70
 *   hci_set_ad                               <= FUN_00055534 @ 0x00055534
 * address symbols (name @ address):
 *   rodata_880f8                             @ 0x000880f8
 *   rodata_f3804                             @ 0x000f3804   [INLINED -- G6 literal batch]
 */
/* Reconstructed hci_set_ad @ 0x00055534 (FUN_00055534; NCS 2.5.1 adv.c). */
#include <stddef.h>
#include <stdint.h>

struct bt_data_record {
    uint8_t type;
    uint8_t data_len;
    const uint8_t *data;
};
struct bt_ad {
    const struct bt_data_record *data;
    size_t len;
};
struct log_record {
    uint32_t count;
    const char *message;
};

extern void *bt_hci_cmd_create(uint16_t opcode, uint32_t payload_size); /* FUN_00053cd4 */
extern uint8_t *net_buf_simple_add(void *simple, uint32_t length); /* FUN_0005f5d0 */
extern void memset_bytes(void*, int, int); /* FUN_00086c78 */
extern void *memcpy(void *, const void *, size_t); /* FUN_00086c04 */
extern void net_buf_unref(int); /* FUN_0005f24c */
extern int bt_hci_cmd_send_sync(uint16_t opcode, void *buffer, void *response);
extern void z_log_msg_runtime_create(unsigned int, unsigned int, unsigned int, unsigned int);
#define bt_hci_cmd_send_sync bt_hci_cmd_send_sync
#define log_message z_log_msg_runtime_create
#define hci_set_ad hci_set_ad

int hci_set_ad(uint16_t opcode, const struct bt_ad *ad, size_t ad_len)
{
    void *buffer = bt_hci_cmd_create(opcode, 0x20u);
    if (buffer == 0) {
        return -105;
    }

    uint8_t *set_data = net_buf_simple_add((uint8_t *)buffer + 0x0c, 0x20u);
    memset_bytes(set_data, 0u, 0x20u);
    uint8_t used = 0u;

    for (size_t i = 0; i < ad_len; ++i) {
        for (size_t j = 0; j < ad[i].len; ++j) {
            const struct bt_data_record *entry = &ad[i].data[j];
            uint32_t length = entry->data_len;
            uint8_t type = entry->type;
            uint32_t value_offset = (uint32_t)used + 2u;

            if (length + value_offset > 0x1fu) {
                length = 0x1fu - value_offset;
                if (type != 9u || (int32_t)length < 1) {
                    struct log_record record = {
                        2u, (const char *)((unsigned long)"Too big advertising data") /*=0xf3804*/
                    };
                    log_message((const void *)((unsigned long)&rodata_880f8) /*=0x880f8*/, 0x1040u,
                                &record, 0u);
                    net_buf_unref(buffer);
                    return -22;
                }
                type = 8u;
            }

            set_data[(uint8_t)(used + 1u)] = (uint8_t)length + 1u;
            set_data[(uint8_t)(used + 2u)] = type;
            memcpy(set_data + (uint8_t)value_offset + 1u,
                   entry->data, (uint8_t)length);
            used = (uint8_t)(used + (uint8_t)length + 2u);
        }
    }

    set_data[0] = used;
    return bt_hci_cmd_send_sync(opcode, buffer, 0);
}

/* ---- ble_conn_addr_and_params_valid.c ---- */
/* readable reconstruction; identity: FUN_00055614 @ 0x00055614
 * public-name: ble_conn_addr_and_params_valid
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ble_conn_addr_and_params_valid           <= FUN_00055614 @ 0x00055614
 *   memcmp                                   <= FUN_00086be4 @ 0x00086be4
 * address symbols (name @ address):
 *   rodata_f2b3a                             @ 0x000f2b3a
 *   g_ble_dev_state                          @ 0x20002000
 */
/* Reconstructed FUN_00055614 @ 0x55614  (parity: 300/300 trials, PROVEN) */
extern int memcmp(unsigned int,unsigned int,int,unsigned int,unsigned int);
unsigned int ble_conn_addr_and_params_valid(unsigned char* param_1,unsigned int param_2,unsigned int param_3,unsigned int param_4){
  int iVar1=((unsigned long)&g_ble_dev_state) /*=0x20002000*/;
  unsigned int uVar4=*(unsigned int*)(param_1+4);
  int iVar2,iVar3;
  if(((int)(uVar4<<0x15)>=0) &&
     (iVar3=*(int*)(param_1+0x10), (iVar3==0 || (uVar4&1)!=0))){
    if(*(volatile unsigned char *)(((unsigned long)&g_ble_dev_state) /*=0x20002000*/+7) <= (unsigned int)*param_1) return 0;
    iVar2=memcmp((unsigned int)*param_1*7+((unsigned long)&g_ble_dev_state) /*=0x20002000*/,((unsigned long)&rodata_f2b3a) /*=0xf2b3a*/,7,*(volatile unsigned char *)(((unsigned long)&g_ble_dev_state) /*=0x20002000*/+7),param_4);
    if(iVar2==0) return 0;
    if(((uVar4&1)==0)&&(*(volatile unsigned char *)(iVar1+0x70)<9)&&(*(unsigned int*)(param_1+8)<0xa0)) return 0;
    if((uVar4&0x30)==0){
      if(((int)(uVar4<<0x1b)>=0)&&(iVar3!=0)) goto L662;
    } else {
      if(iVar3==0) return 0;
      if((int)(uVar4<<0x1b)>=0) goto L662;
    }
    {
      unsigned int v8=*(unsigned int*)(param_1+8), vc=*(unsigned int*)(param_1+0xc);
      if((v8<=vc)&&(v8>0x1f)&&(vc<0x4001)){
        L662:
        if((uVar4&0x38000)!=0x38000) return 1;
        return 0;
      }
    }
  }
  return 0;
}

/* ---- ble_conn_addr_resolve_or_create.c ---- */
/* readable reconstruction; identity: FUN_000556b0 @ 0x000556b0
 * public-name: ble_conn_addr_resolve_or_create
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   adv_is_directed                          <= FUN_00055698 @ 0x00055698
 *   ble_conn_addr_resolve_or_create          <= FUN_000556b0 @ 0x000556b0
 *   ble_conn_set_state                       <= FUN_00056704 @ 0x00056704
 *   ble_conn_le_alloc                        <= FUN_00056e34 @ 0x00056e34
 *   bt_conn_lookup_and_log_valid             <= FUN_00056ea8 @ 0x00056ea8
 * address symbols (name @ address):
 *   rodata_f2b33                             @ 0x000f2b33
 *   g_ble_dev_state                          @ 0x20002000
 */
/* Reconstructed FUN_000556b0 @ 0x556b0  (parity: 300/300 trials, PROVEN) */
extern int adv_is_directed(unsigned long);
extern void ble_conn_set_state(int, int);
extern int ble_conn_le_alloc(unsigned int,unsigned int);
extern int bt_conn_lookup_and_log_valid(unsigned int,void*);
unsigned int ble_conn_addr_resolve_or_create(unsigned char* param_1,int* param_2){
  unsigned char uVar1=*param_1;
  int iVar2; unsigned int uVar3;
  *(volatile unsigned char *)(((unsigned long)&g_ble_dev_state) /*=0x20002000*/+0x6f)=uVar1;
  iVar2=adv_is_directed(param_1);
  if(iVar2==0){
    iVar2=ble_conn_le_alloc(uVar1,((unsigned long)&rodata_f2b33) /*=0xf2b33*/);
    if(iVar2!=0){ uVar3=4; ble_conn_set_state(iVar2,uVar3); *param_2=iVar2; return 0; }
  } else {
    iVar2=bt_conn_lookup_and_log_valid(uVar1,param_1+9);
    if(iVar2!=0) return 0xffffffea;
    iVar2=ble_conn_le_alloc(*param_1,(unsigned int)(param_1+9));
    if(iVar2!=0){ uVar3=5; ble_conn_set_state(iVar2,uVar3); *param_2=iVar2; return 0; }
  }
  return 0xfffffff4;
}

/* ================================================================ */
/* member unit: g1_ble_08.c */
/* ================================================================ */
/*
 * Cohesive translation unit for the `ble' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 3 functions below were 3 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   legacy_advertising_connection_restart.c
 *   ble_rng_seed_from_uptime.c
 *   ble_rng_get_random_bytes.c
 */
/* ---- legacy_advertising_connection_restart.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_00055aac @ 0x00055aac
 * public-name: legacy_advertising_connection_restart
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   z_log_msg_runtime_create                 <= FUN_0004d944 @ 0x0004d944
 *   bt_id_set_adv_random_addr                <= FUN_00055454 @ 0x00055454
 *   adv_is_directed                          <= FUN_00055698 @ 0x00055698
 *   ble_conn_addr_resolve_or_create          <= FUN_000556b0 @ 0x000556b0
 *   legacy_advertising_connection_restart    <= FUN_00055aac @ 0x00055aac
 *   ble_conn_unref                           <= FUN_000566a4 @ 0x000566a4
 *   ble_conn_set_state                       <= FUN_00056704 @ 0x00056704
 *   deref_conn_field0                        <= FUN_0008117a @ 0x0008117a
 *   atomic_and_1                             <= FUN_00081180 @ 0x00081180
 *   bt_le_adv_set_enable_legacy              <= FUN_000812d2 @ 0x000812d2
 * address symbols (name @ address):
 *   rodata_880f8                             @ 0x000880f8
 *   rodata_f3857                             @ 0x000f3857   [INLINED -- G6 literal batch]
 *   g_bt_le_legacy_adv                       @ 0x20002018
 *   g_ble_adv_ctx_flags                      @ 0x20002028
 */
/* Reconstructed FUN_00055aac @ 0x55aac
 * Readable identity: legacy_advertising_connection_restart.
 * Raw/address backmap: FUN_00055aac @ 0x00055aac.
 */
#include <stdint.h>
#include "g1_ble.h"

extern unsigned int deref_conn_field0(unsigned int*); /* atomic_get */
extern int adv_is_directed(unsigned long); /* adv_is_directed */
extern int bt_id_set_adv_random_addr(unsigned char*, int, int, unsigned char*); /* legacy advertising configure */
extern void z_log_msg_runtime_create(unsigned int, unsigned int, unsigned int, unsigned int);
extern void ble_conn_unref(int); /* bt_conn_unref */
extern void ble_conn_set_state(int, int); /* bt_conn_set_state */
extern long atomic_and_1(volatile long*, long); /* atomic_and */

void legacy_advertising_connection_restart(void)
{
    volatile uint32_t *const flags = (volatile uint32_t *)((unsigned long)&g_ble_adv_ctx_flags) /*=0x20002028*/;
    void *connection = 0;
    uint8_t option = 0;

    if ((deref_conn_field0(flags) & 0x4000U) == 0U) return;
    if ((deref_conn_field0(flags) & 0x80U) != 0U) return;
    if ((deref_conn_field0(flags) & 0x400U) == 0U) return;

    if (ble_conn_addr_resolve_or_create((void *)((unsigned long)g_bt_le_legacy_adv) /*=0x20002018*/, &connection) != 0) return;
    {
        uint32_t directed = adv_is_directed((void *)((unsigned long)g_bt_le_legacy_adv) /*=0x20002018*/);
        uint32_t mode = ((((deref_conn_field0(flags) >> 14) & 1U) ^ 1U) << 1);
        if ((deref_conn_field0(flags) & 0x400U) != 0U) mode |= 1U;
        if ((deref_conn_field0(flags) & 0x2000U) != 0U) mode |= 4U;

        {
            int error = bt_id_set_adv_random_addr((void *)((unsigned long)g_bt_le_legacy_adv) /*=0x20002018*/, mode,
                                      directed, &option);
            if (error != 0) {
                uint32_t package[3] = { 3U, ((unsigned long)"Controller cannot resume connectable advertising (%d)") /*=0xf3857*/, (uint32_t)error };
                z_log_msg_runtime_create(((unsigned long)&rodata_880f8) /*=0x880f8*/, 0x1840U, package, 0U);
                return;
            }
        }

        if (bt_le_adv_set_enable_legacy((void *)((unsigned long)g_bt_le_legacy_adv) /*=0x20002018*/, 1U) == 0) {
            ble_conn_unref(connection);
            return;
        }
        ble_conn_set_state(connection, directed);
        {
            uint32_t old = atomic_and_1(flags, 0xffffbfffU);
            ble_conn_unref(connection);
            if ((old & 0x4000U) != 0U) {
                (void)__atomic_fetch_or((uint32_t *)flags, 0x4000U,
                                        __ATOMIC_SEQ_CST);
            }
        }
    }
}

/* ---- ble_rng_seed_from_uptime.c ---- */
/* readable reconstruction; identity: FUN_00055bf8 @ 0x00055bf8
 * public-name: ble_rng_seed_from_uptime
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   z_log_msg_runtime_create                 <= FUN_0004d944 @ 0x0004d944
 *   bt_hci_le_rand                           <= FUN_00053e74 @ 0x00053e74
 *   ble_rng_seed_from_uptime                 <= FUN_00055bf8 @ 0x00055bf8
 *   tc_hmac_prng_reseed                      <= FUN_00080692 @ 0x00080692
 * address symbols (name @ address):
 *   rodata_88148                             @ 0x00088148
 *   rodata_f394f                             @ 0x000f394f
 *   g_hmac_prng_ctx                          @ 0x20006000
 */
/* Reconstructed FUN_00055bf8 @ 0x55bf8  (parity: 300/300 trials, PROVEN) */
extern long long thunk_FUN_00074f68(void);
extern int tc_hmac_prng_reseed(unsigned, void*, int, void*, int);
static int ble_rng_seed_from_uptime(void){
    unsigned char auStack_30[36];
    unsigned local_50, uStack_4c, local_38, local_34;
    int iVar1 = bt_hci_le_rand(auStack_30, 0x20);
    if (iVar1 == 0){
        long long lVar3 = thunk_FUN_00074f68();
        unsigned long long prod = (unsigned long long)(lVar3 * 1000);
        uStack_4c = (unsigned)(prod >> 32);
        local_50 = ((unsigned)prod >> 0xf) | (uStack_4c << 17);
        uStack_4c = uStack_4c >> 0xf;
        int iVar2 = tc_hmac_prng_reseed(((unsigned long)&g_hmac_prng_ctx) /*=0x20006000*/, auStack_30, 0x20, &local_50, 8);
        if (iVar2 == 0){
            local_34 = ((unsigned long)&rodata_f394f) /*=0xf394f*/;
            local_38 = 2;
            iVar1 = -5;
            z_log_msg_runtime_create(((unsigned long)&rodata_88148) /*=0x88148*/, 0x1040, &local_38, 0);
        }
    }
    (void)uStack_4c; (void)local_34;
    return iVar1;
}

/* ---- ble_rng_get_random_bytes.c ---- */
/* readable reconstruction; identity: FUN_00055c64 @ 0x00055c64
 * public-name: ble_rng_get_random_bytes
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   z_log_msg_runtime_create                 <= FUN_0004d944 @ 0x0004d944
 *   bt_hci_le_rand                           <= FUN_00053e74 @ 0x00053e74
 *   ble_rng_seed_from_uptime                 <= FUN_00055bf8 @ 0x00055bf8
 *   ble_rng_get_random_bytes                 <= FUN_00055c64 @ 0x00055c64
 *   tc_hmac_prng_init                        <= FUN_00080652 @ 0x00080652
 * address symbols (name @ address):
 *   rodata_88148                             @ 0x00088148
 *   rodata_f3966                             @ 0x000f3966
 *   g_hmac_prng_ctx                          @ 0x20006000
 */
/* Reconstructed FUN_00055c64 @ 0x55c64  (parity: 300/300 trials, PROVEN) */

static int ble_rng_seed_from_uptime(void);
extern int tc_hmac_prng_init(int,void*,int);

int ble_rng_get_random_bytes(void)
{
    unsigned char buf[24];
    int iVar1 = bt_hci_le_rand(buf, 8);
    if (iVar1 == 0) {
        iVar1 = tc_hmac_prng_init(((unsigned long)&g_hmac_prng_ctx) /*=0x20006000*/, buf, 8);
        if (iVar1 == 0) {
            struct { int f0; int f4; } s;
            s.f0 = 2;
            s.f4 = ((unsigned long)&rodata_f3966) /*=0xf3966*/;
            iVar1 = -5;
            z_log_msg_runtime_create(((unsigned long)&rodata_88148) /*=0x88148*/, 0x1040, &s, 0);
        } else {
            iVar1 = ble_rng_seed_from_uptime();
        }
    }
    return iVar1;
}

