"""Authoritative derivation of the COMPILABLE input set (R2).

The tree that compiles is *not* the canonical evidence tree.  It is:

  * every entry of ``recon/generated/app_retained_sources.cmake`` (1,609) and
    ``recon/generated/net_retained_sources.cmake`` (923) -- these resolve into
    ``recon/symbolized/{app,net}``.  The lists are generated by
    ``tools/gen_retained_sources.py`` from ``recon/ownership/adoption_manifest.json``
    and encode 677 app / 312 net manifest exclusions.  A directory glob over
    ``recon/symbolized/app`` would pick up 532 files the build deliberately does
    NOT compile, so the list is the authority, never the directory.
  * the ``*.inc`` fragments those sources ``#include`` (the G6-B3 link failure
    proved these are compiled content: every literal scan in the repository
    enumerated ``*.c``/``*.h`` only, and an object was withdrawn while an
    ``.inc`` still referenced it);
  * the hand-written integration TUs in ``recon/application/{app,net}/src``;
  * the generated ``.rodata`` TUs in ``recon/application/rodata``;
  * the pin/declaration artifacts the withdraw-transaction has to edit in the
    same breath as an inline: ``recon/symbols/g1_{app,net}_globals.ld`` and
    ``recon/symbols/g1_{app,net}_symbols.h``.

Files the build compiles but which this pipeline must NEVER transform (they are
in a protected tree, R1) are reported separately as ``quarantined_protected``:
the app CMakeLists pulls 2 sources straight out of ``recon/app/src`` and the net
CMakeLists pulls 34 out of ``recon/net/src``.
"""

from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass, field

# PYTHONSAFEPATH=1 is mandatory in this repository (a root-level struct.py
# otherwise shadows the stdlib), and it also removes the script's own directory
# from sys.path -- so sibling modules must be put back explicitly.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from guard import REPO_ROOT, is_protected  # noqa: E402

GENERATED = os.path.join(REPO_ROOT, "recon", "generated")
_CMAKE_SRC = re.compile(r'"?\$\{CMAKE_CURRENT_LIST_DIR\}/([^"\s)]+)"?')
_INCLUDE_INC = re.compile(r'#\s*include\s+"([^"]+\.inc)"')


def _cmake_paths(cmake_file: str) -> list[str]:
    base = os.path.dirname(cmake_file)
    with open(cmake_file, encoding="utf-8") as fh:
        text = fh.read()
    return [
        os.path.normpath(os.path.join(base, m.group(1)))
        for m in _CMAKE_SRC.finditer(text)
    ]


@dataclass
class InputSet:
    #: files this pipeline is allowed to transform, repo-relative, sorted
    transformable: list[str] = field(default_factory=list)
    #: build inputs that are compiled but sit in a protected tree (R1)
    quarantined_protected: list[str] = field(default_factory=list)
    #: provenance, for the MANIFEST
    provenance: dict = field(default_factory=dict)


def rel(path: str) -> str:
    return os.path.relpath(os.path.abspath(path), REPO_ROOT).replace(os.sep, "/")


def derive() -> InputSet:
    transformable: set[str] = set()
    protected: set[str] = set()
    prov: dict = {}

    retained_counts = {}
    for core in ("app", "net"):
        cmake = os.path.join(GENERATED, f"{core}_retained_sources.cmake")
        paths = _cmake_paths(cmake)
        retained_counts[core] = len(paths)
        for p in paths:
            (protected if is_protected(p) else transformable).add(rel(p))
    prov["retained_sources"] = retained_counts

    # .inc fragments reachable from the retained sources
    inc: set[str] = set()
    for r in sorted(transformable):
        ap = os.path.join(REPO_ROOT, r)
        if not ap.endswith(".c"):
            continue
        with open(ap, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        for m in _INCLUDE_INC.finditer(text):
            cand = os.path.normpath(os.path.join(os.path.dirname(ap), m.group(1)))
            if os.path.exists(cand):
                inc.add(rel(cand))
    transformable |= inc
    prov["inc_fragments"] = sorted(inc)

    # sources named directly by the two CMakeLists (hand-written wiring, the
    # canonical files the build pulls in, and anything else spelled inline)
    named_direct = {"app": [], "net": []}
    for core in ("app", "net"):
        cml = os.path.join(REPO_ROOT, "recon", "application", core, "CMakeLists.txt")
        base = os.path.dirname(cml)
        with open(cml, encoding="utf-8") as fh:
            text = fh.read()
        for m in re.finditer(r"\$\{CMAKE_CURRENT_LIST_DIR\}/([^\"\s)]+\.c)", text):
            p = os.path.normpath(os.path.join(base, m.group(1)))
            if not os.path.exists(p):
                continue
            named_direct[core].append(rel(p))
            (protected if is_protected(p) else transformable).add(rel(p))
        # relative `src/foo.c` spellings in target_sources()
        for m in re.finditer(r"^\s+(src/[A-Za-z_0-9./]+\.c)\s*$", text, re.M):
            p = os.path.normpath(os.path.join(base, m.group(1)))
            if os.path.exists(p):
                named_direct[core].append(rel(p))
                transformable.add(rel(p))
    prov["cmakelists_direct"] = {k: len(v) for k, v in named_direct.items()}

    # generated .rodata TUs
    rod = os.path.join(REPO_ROOT, "recon", "application", "rodata")
    rodata = [rel(os.path.join(rod, f)) for f in sorted(os.listdir(rod)) if f.endswith(".c")]
    transformable |= set(rodata)
    prov["rodata_tus"] = len(rodata)

    # pin / declaration artifacts touched by the withdraw transaction
    artefacts = [
        "recon/symbols/g1_app_globals.ld",
        "recon/symbols/g1_net_globals.ld",
        "recon/symbols/g1_app_symbols.h",
        "recon/symbols/g1_net_symbols.h",
    ]
    for a in artefacts:
        if os.path.exists(os.path.join(REPO_ROOT, a)):
            transformable.add(a)
    prov["pin_artifacts"] = artefacts

    return InputSet(
        transformable=sorted(transformable),
        quarantined_protected=sorted(protected),
        provenance=prov,
    )


if __name__ == "__main__":  # pragma: no cover - manual probe
    s = derive()
    print("transformable:", len(s.transformable))
    print("quarantined (protected trees, compiled):", len(s.quarantined_protected))
    for k, v in s.provenance.items():
        print(" ", k, v if not isinstance(v, list) else len(v))
