/*
 * Cohesive translation unit for the `ipc' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 3 functions below were 3 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   st25dv_mailbox_write_with_retry.c
 *   ipc_service_send_with_retry.c
 *   dev_send_cmd16_payload.c
 */

/* File-scope forward declarations for every struct/union tag this
 * unit names.  Without them a tag whose only appearance in a member
 * is inside a parameter list has PARAMETER-LIST scope, so two
 * textually IDENTICAL declarations in two members declare two
 * different incomplete types and the second is a conflicting
 * redeclaration (C11 6.2.1p7).  Incomplete-type forward
 * declarations emit no code. */
struct part;
/* ---- st25dv_mailbox_write_with_retry.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_00024fe8 @ 0x00024fe8
 * public-name: st25dv_mailbox_write_with_retry
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   st25dv_mailbox_send_message              <= FUN_00024f78 @ 0x00024f78
 *   st25dv_mailbox_write_with_retry          <= FUN_00024fe8 @ 0x00024fe8
 *   pt_write_frame_type3                     <= FUN_0007c3d0 @ 0x0007c3d0
 * address symbols (name @ address):
 *   g_st25dv_mailbox_msg                     @ 0x20007a14
 */
/* Reconstructed FUN_00024fe8 @ 0x24fe8  (parity: 300/300 trials, PROVEN) */

extern int pt_write_frame_type3(unsigned int, unsigned int);
extern unsigned int st25dv_mailbox_send_message(void);

unsigned int st25dv_mailbox_write_with_retry(unsigned int param_1, unsigned int param_2)
{
    int iVar1;
    unsigned int uVar2;
    unsigned short selector = (unsigned short)param_2;

    iVar1 = pt_write_frame_type3(selector, param_1);
    if (iVar1 == -1) {
        *(volatile unsigned int *)((unsigned long)&g_st25dv_mailbox_msg) /*=0x20007a14*/ = 0x014040e1U;
        uVar2 = st25dv_mailbox_send_message();
        pt_write_frame_type3(selector, param_1);
    } else {
        uVar2 = 0;
    }
    return uVar2;
}

/* ---- ipc_service_send_with_retry.c ---- */
#include "../../../headers/g1_log.h"
/* readable reconstruction; identity: FUN_0002563c @ 0x0002563c
 * public-name: ipc_service_send_with_retry
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ipc_service_send_with_retry              <= FUN_0002563c @ 0x0002563c
 *   ipc_send_packet_ch2005                   <= FUN_0007ca18 @ 0x0007ca18
 * address symbols (name @ address):
 *   rodata_9f1af                             @ 0x0009f1af   [INLINED -- G6 literal batch]
 *   g_st25dv_dev                             @ 0x20007a44
 */
/* Reconstructed FUN_0002563c @ 0x2563c  (parity: 300/300 trials, PROVEN) */

extern int ipc_send_packet_ch2005(int,int);
int ipc_service_send_with_retry(int param_1)
{
    volatile int *piVar1 = (volatile int*)((unsigned long)&g_st25dv_dev) /*=0x20007a44*/;
    if (param_1 == 0 || *piVar1 == 0) {
        log_message(((unsigned long)"input param valid \n") /*=0x9f1af*/);
        return -1;
    }
    int iVar3 = 10;
    int iVar2;
    do {
        iVar2 = ipc_send_packet_ch2005(*piVar1, param_1);
        if (iVar2 == 0) {
            return 0;
        }
        iVar3 = iVar3 - 1;
    } while (iVar3 != 0);
    return iVar2;
}

/* ---- dev_send_cmd16_payload.c ---- */
/* readable reconstruction; identity: FUN_00025670 @ 0x00025670
 * public-name: dev_send_cmd16_payload
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   dev_send_cmd16_payload                   <= FUN_00025670 @ 0x00025670
 *   ipc_transport_ops_dispatch               <= FUN_0007c85e @ 0x0007c85e
 *   sleep_fixed_33_ticks                     <= FUN_0007c87a @ 0x0007c87a
 *   memcpy                                   <= FUN_00086c04 @ 0x00086c04
 * address symbols (name @ address):
 *   rodata_9f1eb                             @ 0x0009f1eb   [INLINED -- G6 literal batch]
 */
/* Reconstructed FUN_00025670 @ 0x25670 CFG_VERIFY_CALL_ARITIES=3,4,0,2 */
#include <stdint.h>
#include "g1_ipc.h"
extern void memcpy(int, int, int);
extern void sleep_fixed_33_ticks(void);
struct part { uint8_t *data; uint32_t length; uint8_t type; };
int dev_send_cmd16_payload(uint32_t *dev, uint32_t op, uint32_t command,
                 uint32_t value, uint32_t n)
{
    uint8_t bytes[n + 2];
    bytes[0] = command >> 8; bytes[1] = command;
    memcpy(bytes + 2, (const uint8_t *)(uintptr_t)value, n);
    struct part p = {bytes, n + 2, 2};
    int r = ipc_transport_ops_dispatch(*dev, &p, 1, op);
    sleep_fixed_33_ticks();
    if (r < 0) log_message(((unsigned long)"_st25dv_write  ret %d \n") /*=0x9f1eb*/, r);
    return r;
}

