/*
 * Cohesive translation unit for the `analytics' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 7 functions below were 7 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   load_burial_point.c
 *   debug_print_burial_point_date.c
 *   update_burial_point_day_index.c
 *   enter_wear_burial_point.c
 *   enter_dashboard_burial_point.c
 *   exit_dashboard_burial_point.c
 *   burial_point_record_info_init.c
 */
/* ---- load_burial_point.c ---- */
#include "g1_app_symbols.h"
#include "../../../headers/g1_log.h"
#include "../../../headers/g1_dedupe.h"
#include "g1_analytics.h"
#include <stdint.h>
/* readable reconstruction; identity: FUN_000230e0 @ 0x000230e0
 * public-name: load_burial_point
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   flash_settings_read                      <= FUN_000225b4 @ 0x000225b4
 *   sys_rand32_get                           <= FUN_00052c40 @ 0x00052c40
 *   memset_bytes                             <= FUN_00086c78 @ 0x00086c78
 * address symbols (name @ address):
 *   rodata_9e67c                             @ 0x0009e67c   [INLINED -- G6 literal batch]
 *   rodata_9e777                             @ 0x0009e777   [INLINED -- G6 literal batch]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 */
/* Reconstructed load_burial_point @ 0x230e0  (parity: 300/300 trials, PROVEN) */

extern int flash_settings_read(unsigned int, void*, int, unsigned int, unsigned int);
extern unsigned int sys_rand32_get(void);

unsigned int load_burial_point(int param_1, unsigned int param_2, unsigned int param_3, unsigned int param_4)
{
    int iVar1;
    unsigned int uVar2;
    unsigned int uVar3;
    unsigned char *base = (unsigned char*)(param_1 + 0x1000);

    iVar1 = flash_settings_read(0x135000, (void*)(param_1 + 0x10c6), 0xc0, param_4, param_4);
    if (iVar1 == 0) {
        uVar3 = 0;
        if ((*(volatile short *)(base + 0xda) == -1) || (*(volatile char *)(base + 0xdc) == 0)) {
            uVar2 = sys_rand32_get();
            memset_bytes(base + 0xca, 0, 0xbc);
            *(volatile unsigned char *)(base + 0xda) = 7;
            *(volatile unsigned int *)(base + 0xc6) = uVar2;
            *(volatile unsigned char *)(base + 0xdc) = 1;
        }
    } else {
        if (1 < *(volatile int *)((unsigned long)&g_log_level) /*=0x2000230c*/) {
            G1_LOG_ROUTE(*(volatile unsigned int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0, ((unsigned long)"%s(): burial_point read error!\n") /*=0x9e67c*/, ((unsigned long)"load_burial_point") /*=0x9e777*/);
        }
        uVar3 = 0xffffffff;
    }
    return uVar3;
}

/* ---- debug_print_burial_point_date.c ---- */
/* readable reconstruction; identity: FUN_0004a2a4 @ 0x0004a2a4
 * public-name: debug_print_burial_point_date
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   unix_timestamp_to_datetime               <= FUN_0004a1b8 @ 0x0004a1b8
 *   debug_print_burial_point_date            <= FUN_0004a2a4 @ 0x0004a2a4
 *   compute_day_of_week                      <= FUN_0007d280 @ 0x0007d280
 *   get_localized_weekday_name               <= FUN_0007d4b2 @ 0x0007d4b2
 * address symbols (name @ address):
 *   rodata_9bbbf                             @ 0x0009bbbf
 */
/* Reconstructed FUN_0004a2a4 @ 0x4a2a4  (parity: 300/300 trials, PROVEN) */
extern int compute_day_of_week(int,int,int);
extern int get_localized_weekday_name(int);
void debug_print_burial_point_date(int param_1){
  uint16_t calendar[6]={0};
  unix_timestamp_to_datetime(param_1, calendar);
  uint32_t uVar3 = calendar[0];
  uint32_t uVar1 = calendar[1];
  uint32_t uVar4 = calendar[2];
  log_message(((unsigned long)&rodata_9bbbf) /*=0x9bbbf*/, param_1, uVar3, uVar1, uVar4,
              calendar[3], calendar[4], calendar[5]);
  int cVar2 = compute_day_of_week(uVar3, uVar1, uVar4);
  get_localized_weekday_name((int)(uint8_t)(cVar2 + 0x3b));
}

/* ---- update_burial_point_day_index.c ---- */
/* readable reconstruction; identity: FUN_0004a5b0 @ 0x0004a5b0
 * public-name: update_burial_point_day_index
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   unix_timestamp_to_datetime               <= FUN_0004a1b8 @ 0x0004a1b8
 *   update_burial_point_day_index            <= FUN_0004a5b0 @ 0x0004a5b0
 *   get_system_unix_time                     <= FUN_0007d216 @ 0x0007d216
 * address symbols (name @ address):
 *   rodata_f0310                             @ 0x000f0310   [INLINED -- G6 literal batch]
 *   rodata_f04c1                             @ 0x000f04c1   [INLINED -- G6 literal batch]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 */
/* Reconstructed FUN_0004a5b0 @ 0x4a5b0. */

extern uint32_t get_system_unix_time(void);

#define STATE() ((volatile uint8_t *)get_device_info())

static inline uint8_t state_index(volatile uint8_t *state)
{
  return state[0x10db];
}

int update_burial_point_day_index(uint32_t context,uint32_t unused_2,
                 uint32_t unused_3,uint32_t unused_4)
{
  uint16_t calendar[6] = {0};
  uint32_t now = get_system_unix_time();
  (void)unused_2; (void)unused_3; (void)unused_4;
  unix_timestamp_to_datetime(now,calendar);

  uint16_t year = calendar[0];
  uint16_t month = calendar[1];
  uint16_t day = calendar[2];
  if (year < 2025 && ((uint16_t)(month | day) < 2)) {
    if (*(volatile int *)((unsigned long)&g_log_level) /*=0x2000230c*/ > 1) {
      if (*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0)
        log_message(((unsigned long)"%s(): burial point date was not init!\n") /*=0xf0310*/,((unsigned long)"update_burial_point_day_index") /*=0xf04c1*/,day,0,context);
      else
        debug_print(((unsigned long)"%s(): burial point date was not init!\n") /*=0xf0310*/,((unsigned long)"update_burial_point_day_index") /*=0xf04c1*/,day,0,context);
    }
    return -1;
  }

  volatile uint8_t *state = STATE();
  if (state_index(state) > 6)
    STATE()[0x10db] = 0;

  state = STATE();
  volatile uint8_t *index_state = STATE();
  unsigned index = state_index(index_state);
  if (*(volatile int16_t *)(state + 0x10de + index * 12) == (int16_t)year) {
    state = STATE(); index_state = STATE(); index = state_index(index_state);
    if (state[0x10e0 + index * 12] == (uint8_t)month) {
      state = STATE(); index_state = STATE(); index = state_index(index_state);
      if (state[0x10e1 + index * 12] == (uint8_t)day)
        return 0;
    }
  }

  unsigned selected;
  for (selected = 0; selected < 7; ++selected) {
    state = STATE();
    if (state_index(state) == (uint8_t)selected)
      continue;
    state = STATE();
    unsigned offset = selected * 12;
    if (*(volatile int16_t *)(state + 0x10de + offset) != (int16_t)year)
      continue;
    state = STATE();
    if (state[0x10e0 + offset] != (uint8_t)month)
      continue;
    state = STATE();
    if (state[0x10e1 + offset] != (uint8_t)day)
      continue;
    STATE()[0x10db] = (uint8_t)selected;
    goto publish;
  }

  state = STATE();
  state[0x10db] = (uint8_t)(state[0x10db] + 1);
  state = STATE();
  if (state_index(state) > 6)
    STATE()[0x10db] = 0;

publish:
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  *(volatile int16_t *)(state + 0x10de + index * 12) = (int16_t)year;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  state[0x10e0 + index * 12] = (uint8_t)month;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  state[0x10e1 + index * 12] = (uint8_t)day;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  *(volatile uint16_t *)(state + 0x10e2 + index * 12) = 0;
  *(volatile uint16_t *)(state + 0x10e4 + index * 12) = 0;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  *(volatile uint16_t *)(state + 0x10e6 + index * 12) = 0;
  *(volatile uint16_t *)(state + 0x10e8 + index * 12) = 0;

  state = STATE(); index_state = STATE(); index = state_index(index_state);
  *(volatile int16_t *)(state + 0x1132 + index * 12) = (int16_t)year;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  state[0x1134 + index * 12] = (uint8_t)month;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  state[0x1135 + index * 12] = (uint8_t)day;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  *(volatile uint16_t *)(state + 0x1136 + index * 12) = 0;
  *(volatile uint16_t *)(state + 0x1138 + index * 12) = 0;
  state = STATE(); index_state = STATE(); index = state_index(index_state);
  *(volatile uint16_t *)(state + 0x113a + index * 12) = 0;
  *(volatile uint16_t *)(state + 0x113c + index * 12) = 0;
  return 0;
}

/* ---- enter_wear_burial_point.c ---- */
/* readable reconstruction; identity: FUN_0004a890 @ 0x0004a890
 * public-name: enter_wear_burial_point
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   enter_wear_burial_point                  <= FUN_0004a890 @ 0x0004a890
 *   k_uptime_get_10                          <= FUN_0007daa4 @ 0x0007daa4
 *   get_current_burial_point_type            <= FUN_0007dac0 @ 0x0007dac0
 * address symbols (name @ address):
 *   rodata_f0337                             @ 0x000f0337   [INLINED -- G6 literal batch]
 *   rodata_f04a9                             @ 0x000f04a9   [INLINED -- G6 literal batch]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 */
/* Reconstructed FUN_0004a890 @ 0x4a890  (parity: 300/300 trials, PROVEN) */
void enter_wear_burial_point(void){
  int iVar1; unsigned uVar2; unsigned long long uVar3;
  iVar1 = get_device_info();
  if (*(volatile unsigned char *)(iVar1+0x10ac) != 1){
    uVar2 = get_current_burial_point_type();
    if (uVar2 < 7){
      iVar1 = get_device_info();
      *(volatile unsigned char *)(iVar1+0x10ac) = 1;
      iVar1 = get_device_info();
      *(volatile unsigned char *)(iVar1+0x10ad) = (unsigned char)uVar2;
      iVar1 = get_device_info();
      uVar3 = k_uptime_get_10();
      *(volatile unsigned int *)(iVar1+0x10b2) = (unsigned)(uVar3>>32);
      *(volatile unsigned int *)(iVar1+0x10ae) = (unsigned)uVar3;
      iVar1 = get_device_info();
      iVar1 = uVar2*0xc + iVar1;
      *(volatile int *)(iVar1+0x10e6) = *(volatile int *)(iVar1+0x10e6) + 1;
      iVar1 = get_device_info();
      *(volatile int *)(iVar1+0x10ce) = *(volatile int *)(iVar1+0x10ce) + 1;
      if (1 < *(volatile int *)((unsigned long)&g_log_level) /*=0x2000230c*/){
        if (*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ != 0){
          iVar1 = get_device_info();
          debug_print(((unsigned long)"%s(): [enter_wear_burial_point] start_time is %d\n") /*=0xf0337*/,((unsigned long)"enter_wear_burial_point") /*=0xf04a9*/,*(volatile unsigned int *)(iVar1+0x10ae),*(volatile unsigned int *)(iVar1+0x10b2));
          return;
        }
        iVar1 = get_device_info();
        log_message(((unsigned long)"%s(): [enter_wear_burial_point] start_time is %d\n") /*=0xf0337*/,((unsigned long)"enter_wear_burial_point") /*=0xf04a9*/,*(volatile unsigned int *)(iVar1+0x10ae),*(volatile unsigned int *)(iVar1+0x10b2));
        return;
      }
    }
  }
  return;
}

/* ---- enter_dashboard_burial_point.c ---- */
/* readable reconstruction; identity: FUN_0004a9ec @ 0x0004a9ec
 * public-name: enter_dashboard_burial_point
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   enter_dashboard_burial_point             <= FUN_0004a9ec @ 0x0004a9ec
 *   k_uptime_get_10                          <= FUN_0007daa4 @ 0x0007daa4
 *   get_current_burial_point_type            <= FUN_0007dac0 @ 0x0007dac0
 * address symbols (name @ address):
 *   rodata_f038d                             @ 0x000f038d   [INLINED -- G6 literal batch]
 *   rodata_f0475                             @ 0x000f0475   [INLINED -- G6 literal batch]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 */
/* Reconstructed FUN_0004a9ec @ 0x4a9ec  (parity: 300/300 trials, PROVEN) */

void enter_dashboard_burial_point(void){
    int iVar1 = get_device_info();
    if (*(char*)(iVar1+0x1092) != 1){
        unsigned uVar2 = get_current_burial_point_type();
        if (uVar2 < 7){
            iVar1=get_device_info(); *(char*)(iVar1+0x1092)=1;
            iVar1=get_device_info(); *(char*)(iVar1+0x1093)=(char)uVar2;
            iVar1=get_device_info(); *(unsigned long long*)(iVar1+0x1094)=k_uptime_get_10();
            iVar1=get_device_info(); { int a = (int)(uVar2*0xc) + iVar1; *(int*)(a+0x113a) += 1; }
            iVar1=get_device_info(); *(int*)(iVar1+0x10d6) += 1;
            if (1 < *(int*)((unsigned long)&g_log_level) /*=0x2000230c*/){
                if (*(int*)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ != 0){
                    iVar1=get_device_info();
                    debug_print(((unsigned long)"%s(): [enter_dashboard_burial_point] start_time is %d\n") /*=0xf038d*/,((unsigned long)"enter_dashboard_burial_point") /*=0xf0475*/,*(unsigned*)(iVar1+0x1094),*(unsigned*)(iVar1+0x1098));
                    return;
                }
                iVar1=get_device_info();
                log_message(((unsigned long)"%s(): [enter_dashboard_burial_point] start_time is %d\n") /*=0xf038d*/,((unsigned long)"enter_dashboard_burial_point") /*=0xf0475*/,*(unsigned*)(iVar1+0x1094),*(unsigned*)(iVar1+0x1098));
                return;
            }
        }
    }
}

/* ---- exit_dashboard_burial_point.c ---- */
/* readable reconstruction; identity: FUN_0004aab0 @ 0x0004aab0
 * public-name: exit_dashboard_burial_point
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   get_dashboard_sum_time                   <= FUN_0004a960 @ 0x0004a960
 *   get_current_burial_point_type            <= FUN_0007dac0 @ 0x0007dac0
 *   accumulate_burial_point_duration         <= FUN_0007db50 @ 0x0007db50
 * address symbols (name @ address):
 *   rodata_f03c4                             @ 0x000f03c4   [INLINED -- G6 literal batch]
 *   rodata_f0459                             @ 0x000f0459   [INLINED -- G6 literal batch]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 */
/* Reconstructed exit_dashboard_burial_point @ 0x4aab0  (parity: 300/300 trials, PROVEN) */

extern long long get_dashboard_sum_time(void);
extern unsigned int accumulate_burial_point_duration(void);

/* G7-B2 defect fix.  The body was `unsigned int` and assigned the result of
 * the logging call to the variable it returned.  Both sinks are `void`
 * (recon/headers/g1_log.h).  The shipped function computes no return value:
 * every exit is `add sp, #0xc; pop {r4, r5, pc}` at 0x4ab0a with r0 left
 * holding whatever the last call returned, and the sole caller,
 * ui_DashBoard_task.c:649, discards it.  The `r0v` chain was the decompiler
 * tracking r0's incidental content.  The five-argument shape of the two
 * logging calls is CORRECT and unchanged -- 0x4aaf0..0x4ab04 loads r0, r1, r2,
 * r3 and one stacked word at [sp]. */
void exit_dashboard_burial_point(void)
{
    unsigned int base;
    unsigned int uVar2;
    unsigned long long uVar4;
    unsigned int uVar3;

    base = get_device_info() + 0x1000;
    if (*(volatile unsigned char *)(base + 0x92) != 0) {
        uVar2 = get_current_burial_point_type();
        if (uVar2 < 7) {
            base = get_device_info() + 0x1000;
            *(volatile unsigned char *)(base + 0x92) = 0;
            uVar4 = (unsigned long long)get_dashboard_sum_time();
            uVar3 = (unsigned int)(uVar4 >> 32);
            (void)accumulate_burial_point_duration();
            if (1 < *(volatile int *)((unsigned long)&g_log_level) /*=0x2000230c*/) {
                if (*(volatile unsigned int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0) {
                    base = get_device_info() + 0x1000;
                    log_message(((unsigned long)"%s(): [exit_dashboard_burial_point] sum_time is %d ms,dashboard_sum_time is %d s\n") /*=0xf03c4*/, ((unsigned long)"exit_dashboard_burial_point") /*=0xf0459*/, (unsigned int)uVar4, uVar3, *(volatile unsigned int *)(base + 0xd2));
                } else {
                    base = get_device_info() + 0x1000;
                    debug_print(((unsigned long)"%s(): [exit_dashboard_burial_point] sum_time is %d ms,dashboard_sum_time is %d s\n") /*=0xf03c4*/, ((unsigned long)"exit_dashboard_burial_point") /*=0xf0459*/, (unsigned int)uVar4, uVar3, *(volatile unsigned int *)(base + 0xd2));
                }
            }
        }
    }
}

/* ---- burial_point_record_info_init.c ---- */
/* readable reconstruction; identity: FUN_0004ab3c @ 0x0004ab3c
 * public-name: burial_point_record_info_init
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   memset_bytes                             <= FUN_00086c78 @ 0x00086c78
 * address symbols (name @ address):
 *   rodata_f0416                             @ 0x000f0416   [INLINED -- G6 literal batch]
 *   rodata_f043b                             @ 0x000f043b   [INLINED -- G6 literal batch]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 */
/* Reconstructed burial_point_record_info_init @ 0x4ab3c */


void burial_point_record_info_init(void)
{
  if (*(volatile int32_t *)((unsigned long)&g_log_level) /*=0x2000230c*/ > 2) {
    G1_LOG_ROUTE(*(volatile uint32_t *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0, ((unsigned long)"%s(): burial_point_record_info_init\n") /*=0xf0416*/, ((unsigned long)"burial_point_record_info_init") /*=0xf043b*/);
  }

  uint8_t *runtime = get_device_info();
  memset_bytes(runtime + 0x1092, 0, 0x1a);
  runtime = get_device_info();
  memset_bytes(runtime + 0x10ac, 0, 0x1a);
}

