/*
 * Cohesive translation unit for the `storage' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 4 functions below were 4 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   flash_write_close_ate_marker.c
 *   flash_verify_write_at_current_offset.c
 *   flash_area_write_and_close.c
 *   flash_nrf_get_page_size.c
 */
/* ---- flash_write_close_ate_marker.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_00084e44 @ 0x00084e44
 * public-name: flash_write_close_ate_marker
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   flash_write_padded_entry                 <= FUN_00084dea @ 0x00084dea
 */
/* Reconstructed flash_write_close_ate_marker @ 0x00084e44.
 * Raw/address back-map: FUN_00084e44 / 0x00084e44.
 */
#include <stdint.h>

#define flash_write_padded_entry flash_write_padded_entry
extern int flash_write_padded_entry(uintptr_t peripheral, uint32_t destination,
                                    const void *source, uint32_t length);

void flash_write_close_ate_marker(uintptr_t peripheral, uint32_t destination,
                                  uint8_t marker)
{
    (void)flash_write_padded_entry(peripheral, destination, &marker, 1u);
}

/* ---- flash_verify_write_at_current_offset.c ---- */
/* readable reconstruction; identity: FUN_00084e66 @ 0x00084e66
 * public-name: flash_verify_write_at_current_offset
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   flash_write_byte_and_verify              <= FUN_00084db2 @ 0x00084db2
 *   flash_verify_write_at_current_offset     <= FUN_00084e66 @ 0x00084e66
 */
/* Reconstructed FUN_00084e66 @ 0x84e66  (parity: 300/300 trials, PROVEN) */

extern void flash_write_byte_and_verify(int,unsigned int,unsigned int);
void flash_verify_write_at_current_offset(int param_1,unsigned int param_2)
{
  flash_write_byte_and_verify(param_1,param_2,*(volatile uint32_t *)(param_1 + 8) - 0x18U & 0xfffffff8);
  return;
}

/* ---- flash_area_write_and_close.c ---- */
/* readable reconstruction; identity: FUN_00084e72 @ 0x00084e72
 * public-name: flash_area_write_and_close
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   flash_area_open                          <= FUN_0004e048 @ 0x0004e048
 *   flash_read_boot_swap_ate                 <= FUN_0006403c @ 0x0006403c
 *   nullsub_3                                <= FUN_0007ef7e @ 0x0007ef7e
 *   flash_area_write_and_close               <= FUN_00084e72 @ 0x00084e72
 */
/* Reconstructed FUN_00084e72 @ 0x84e72  (parity: 300/300 trials, PROVEN) */

extern int flash_area_open(unsigned int a, void *b, unsigned int c, unsigned int d, unsigned int e);
extern unsigned int flash_read_boot_swap_ate(int, unsigned char *);
extern void nullsub_3(unsigned int a);

unsigned int flash_area_write_and_close(unsigned int param_1, unsigned int param_2, unsigned int param_3, unsigned int param_4)
{
    int iVar1;
    unsigned int uVar2;
    unsigned int local_c;
    local_c = param_2;
    iVar1 = flash_area_open(param_1 & 0xff, &local_c, param_3, param_4, param_1);
    if (iVar1 == 0) {
        uVar2 = flash_read_boot_swap_ate(local_c, param_2);
        nullsub_3(local_c);
    } else {
        uVar2 = 1;
    }
    return uVar2;
}

/* ---- flash_nrf_get_page_size.c ---- */
/* readable reconstruction; identity: FUN_000851ee @ 0x000851ee
 * public-name: flash_nrf_get_page_size
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   flash_nrf_get_page_size                  <= FUN_000851ee @ 0x000851ee
 */
/* Reconstructed FUN_000851ee @ 0x851ee  (parity: 300/300 trials, PROVEN) */

static unsigned int flash_nrf_get_page_size(void)
{
    return 0x1000;
}

