#!/usr/bin/env python3
"""Emit the shipped CPUAPP rodata STRING objects that were only linker pins.

WHY THIS EXISTS (P4 iteration 21)
---------------------------------
`recon/symbols/g1_app_globals.ld` pins 2,563 `rodata_<hex>` symbols with
`PROVIDE(rodata_XXXX = 0xXXXX)` -- the ORIGINAL image's flash addresses.  Only
the byte-verified TABLES (`recon/data`, emitted as `rodata_0x<hex>`) override
those pins with real objects; 2,128 of the pins are still absolute in the link
(`arm-zephyr-eabi-nm` reports them as class `A`).  Our app image is relocated,
so every one of those addresses now names unrelated bytes.

For a log line that only ever reaches a UART that is a cosmetic defect.  It is
NOT cosmetic when the string is a **format string of a _FORTIFY_SOURCE-checked
printf**: `bt_start()` builds the advertised device name with

    __sprintf_chk(name, 0, 0x20, rodata_9acb2 /* "%s_R_%02X%02X%02X" */,
                  rodata_9ac7c /* "Even G1" */, ...)

and with both operands pointing at relocated garbage the formatted result
overran the 32-byte buffer, `fortify_chk_fail()` printed
"* buffer overflow detected *" and raised K_ERR_KERNEL_OOPS, which reset the
SoC (measured, iteration 21: `VDP dst=0x20011087 cnt=32 fmt=0x9ACB2` followed
by `CHKFAIL lr=0x7B201`).

POLICY
------
Emit a byte-exact object for every absolute `rodata_` pin whose target is a
NUL-terminated printable C string in `app_update.bin` (read through
`tools/extract.py`, never by naive VA subtraction).  Anything else -- tables,
pins into the middle of binary data, strings longer than the scan window --
is left exactly as it is today.  The objects are ordinary
`-fdata-sections` rodata, so `--gc-sections` still drops the ones nothing
references; only strings that are actually reached cost flash.

The declaration in `recon/symbols/g1_app_symbols.h` is
`extern const unsigned char rodata_XXXX[];`, so the definitions use exactly
that type.  A `PROVIDE` is inert once the symbol has a real definition, so no
linker-script edit is required and the parity trees are untouched.

Usage:
  PYTHONSAFEPATH=1 .venv/bin/python recon/application/gen_app_string_rodata.py \
      --elf /private/tmp/g1-i20a-app/zephyr/zephyr.elf \
      -o recon/application/app/src/g1_app_string_rodata.c
"""

import argparse
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(REPO) if os.path.basename(REPO) == "recon" else REPO
sys.path.insert(0, os.path.join(REPO, "tools"))
import extract as E  # noqa: E402

GLOBALS_LD = os.path.join(REPO, "recon", "symbols", "g1_app_globals.ld")
PIN = re.compile(r"PROVIDE\((rodata_[0-9a-fA-F]+)\s*=\s*(0x[0-9a-fA-F]+)\);")
NM = ("/Users/freedomcoder/zephyr-sdk-0.16.5-1/arm-zephyr-eabi/bin/"
      "arm-zephyr-eabi-nm")
SCAN = 260          # bytes scanned for the terminating NUL
MAX_LEN = 255       # longest accepted string body


def printable(data):
    return all(32 <= b < 127 or b in (9, 10, 13) for b in data)


def absolute_pins(elf):
    """Symbols the current link still resolves to an absolute value."""
    if not elf:
        return None
    out = subprocess.run([NM, elf], capture_output=True, text=True).stdout
    return {line.split()[2] for line in out.splitlines()
            if " A rodata_" in line}


def collect(elf):
    pins = PIN.findall(open(GLOBALS_LD, encoding="utf-8").read())
    keep = absolute_pins(elf)
    rows = []
    seen = set()
    for name, addr in pins:
        if keep is not None and name not in keep:
            continue
        if name in seen:
            continue
        value = int(addr, 16)
        data = E.read(value, SCAN)
        end = data.find(b"\0")
        if end <= 0 or end > MAX_LEN:
            continue
        body = data[:end]
        if not printable(body):
            continue
        seen.add(name)
        rows.append((name, value, body))
    rows.sort(key=lambda row: row[1])
    return rows


def emit(rows, out):
    lines = [
        "/* GENERATED by recon/application/gen_app_string_rodata.py -"
        " do not edit.",
        " *",
        " * Byte-exact CPUAPP rodata STRING objects for the `rodata_<hex>`"
        " symbols that",
        " * the cohesive link otherwise resolved to ORIGINAL-image absolute"
        " addresses",
        " * (PROVIDE pins in recon/symbols/g1_app_globals.ld).  See the"
        " generator's",
        " * docstring for the measured failure this closes (the __sprintf_chk"
        " buffer",
        " * overflow in bt_start's device-name formatting).",
        " *",
        " * Bytes are read from app_update.bin through tools/extract.py.  Each"
        " object",
        " * carries its original VA so the mapping stays reversible.",
        " */",
        "",
    ]
    for name, addr, body in rows:
        text = ", ".join("0x%02x" % b for b in body)
        lines.append("/* 0x%05x */ const unsigned char %s[%d] = { %s, 0x00 };"
                     % (addr, name, len(body) + 1, text))
    lines.append("")
    with open(out, "w", encoding="utf-8") as stream:
        stream.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--elf", default=None,
                        help="link whose absolute rodata_ pins to close")
    parser.add_argument("-o", "--output", required=True)
    args = parser.parse_args()
    rows = collect(args.elf)
    emit(rows, args.output)
    total = sum(len(body) + 1 for _, _, body in rows)
    print("emitted %d string objects, %d bytes" % (len(rows), total))


if __name__ == "__main__":
    main()
