#!/usr/bin/env python3
"""Emit the two CPUAPP `.rodata` regions P4 iteration 36 found still unwired.

Both were plain `PROVIDE(rodata_<hex> = 0x<hex>)` numeric pins in
`recon/symbols/g1_app_globals.ld`, i.e. `nm` class `A` in the linked ELF, so the
recovered code read them at the ORIGINAL image address, which in our relocated
build is live but unrelated `.rodata`.

1. `rodata_aae20`, 66,560 B = `[0xaae20, 0xbb220)` -- the display fade/dither
   MASK ATLAS (26 phase rows x 8 frames x 320 B).  `ui_DashBoard_task`'s
   four-step entry fade ANDs the finished dashboard with
   `atlas[order[step]*0x140 + (row % 26)*0xa00 + col]`, and the shipped order
   table `rodata_a8c57` is `01 03 05 07 ...`, whose last frame is 100 % open.
   Reading the atlas from our own image instead ANDs the picture with glyph
   bitmaps and erases it -- the "decay" of report section 35.12.

2. The eight LOCALIZED STRING TABLES `rodata_8a3e0 / _8a4e8 / _8a5f0 / _8a6f8 /
   _8a800 / _8a908 / _8aa10 / _8ab18` (8 x 66 x 4 B) that
   `get_localized_string_ptr` indexes, plus the 3,534-byte string pool
   `rodata_bb220` = `[0xbb220, 0xbbfee)` and the 1-byte empty string
   `rodata_a8ea0` they point into.  The tables hold ABSOLUTE original-image
   addresses, so -- exactly like batch 5's `ptr_record` objects
   (recon/emulator/reports/pointer_rebind.md) -- they are emitted as RELOCATED
   pointers taken from the linker, never as raw absolute words.  Byte equality
   with `app_update.bin` holds MODULO RELOCATION for the tables and EXACTLY for
   the two data objects.

Every byte comes from `app_update.bin` through `tools/extract.py`.

  PYTHONSAFEPATH=1 .venv/bin/python recon/application/gen_app_localized_rodata.py
"""
import os
import struct
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(REPO, "tools"))
import extract  # noqa: E402

ATLAS_VA, ATLAS_LEN = 0xAAE20, 0xBB220 - 0xAAE20      # 66,560
POOL_VA, POOL_LEN = 0xBB220, 0xBBFEE - 0xBB220        # 3,534
EMPTY_VA, EMPTY_LEN = 0xA8EA0, 1
TABLES = [0x8A3E0, 0x8A4E8, 0x8A5F0, 0x8A6F8, 0x8A800, 0x8A908, 0x8AA10, 0x8AB18]
TABLE_ENTRIES = 66                                     # rodata_8ac20-independent: 0x108 / 4
LUT_VA, LUT_LEN = 0xD753A, 0xD793A - 0xD753A           # 1,024  nibble-expansion LUT
GLYPH_VA, GLYPH_LEN = 0xE123A, 0xE5F62 - 0xE123A       # 19,752 icons + 3 glyph runs


def hexrows(data, indent="\t"):
    out = []
    for i in range(0, len(data), 16):
        out.append(indent + " ".join("0x%02x," % b for b in data[i:i + 16]))
    return "\n".join(out)


def main():
    atlas = extract.read(ATLAS_VA, ATLAS_LEN)
    pool = extract.read(POOL_VA, POOL_LEN)
    empty = extract.read(EMPTY_VA, EMPTY_LEN)
    assert len(atlas) == ATLAS_LEN and len(pool) == POOL_LEN
    assert empty == b"\x00", empty

    # ---- file 1: the fade mask atlas -------------------------------------
    p1 = os.path.join(REPO, "recon/application/app/src/g1_app_fade_mask_rodata.c")
    with open(p1, "w") as fh:
        fh.write(
            "/* GENERATED by recon/application/gen_app_localized_rodata.py -- DO NOT EDIT.\n"
            " *\n"
            " * 0x%05x, %d bytes -- the display fade/dither MASK ATLAS,\n"
            " * [0x%05x, 0x%05x), 26 phase rows x 8 frames x 320 B, byte-exact from\n"
            " * app_update.bin through tools/extract.py.\n"
            " *\n"
            " * Readers: ui_DashBoard_task, ui_QuickNote_task, ui_even_ai_task,\n"
            " * ui_translate_task, ui_new_message_task, ui_set_imu_pitch_task,\n"
            " * onboarding_render_step_screen, render_ancs_notification_animation,\n"
            " * navigation_overview_map_display, navigation_panoramic_map_display,\n"
            " * gui_screen_fade_out_transition, display_fade_out_mask_bands.\n"
            " *\n"
            " * Frame occupancy measured from these very bytes (non-zero nibbles):\n"
            " *   frame 0 0.0%%   1 10.2%%   2 18.6%%   3 34.7%%\n"
            " *   frame 4 46.5%%  5 54.6%%   6 63.2%%   7 100.0%%\n"
            " * and the shipped step order rodata_a8c57 is 01 03 05 07 ..., so the\n"
            " * fourth and last entry-fade step ANDs with 0xFF and LEAVES the finished\n"
            " * screen on the panel.  Until this object existed the same code ANDed the\n"
            " * dashboard with whatever our relocated image holds at 0x%05x -- the\n"
            " * interior of the glyph bitmap run rodata_d753a -- and erased it.\n"
            " *\n"
            " * The numeric PROVIDE for this pin is deleted from g1_app_globals.ld, so a\n"
            " * link that failed to retain the object errors out instead of silently\n"
            " * reading our own image again.\n"
            " */\n" % (ATLAS_VA, ATLAS_LEN, ATLAS_VA, ATLAS_VA + ATLAS_LEN, ATLAS_VA)
        )
        fh.write("const unsigned char g1_ro_aae20[%d] __asm__(\"rodata_aae20\") = {\n%s\n};\n"
                 % (ATLAS_LEN, hexrows(atlas)))

    # ---- file 2: the localized string pool + the eight pointer tables ----
    words = {va: struct.unpack("<%dI" % TABLE_ENTRIES,
                               extract.read(va, TABLE_ENTRIES * 4)) for va in TABLES}
    targets = sorted({w for ws in words.values() for w in ws if w})
    outside = [t for t in targets if not (POOL_VA <= t < POOL_VA + POOL_LEN) and t != EMPTY_VA]
    assert not outside, [hex(t) for t in outside]

    p2 = os.path.join(REPO, "recon/application/app/src/g1_app_localized_rodata.c")
    with open(p2, "w") as fh:
        fh.write(
            "/* GENERATED by recon/application/gen_app_localized_rodata.py -- DO NOT EDIT.\n"
            " *\n"
            " * The CPUAPP LOCALIZED STRING resource, which get_localized_string_ptr\n"
            " * (FUN_000456fc) indexes:\n"
            " *\n"
            " *     return *(volatile u32 *)(table + idx * 4);\n"
            " *\n"
            " * i.e. it loads a POINTER out of one of eight 264-byte tables.  Every\n"
            " * on-screen label that is not a clock digit comes through here --\n"
            " * DashBoard_Reflash's `Mon, Jan 1' (idx 0x28+dow and 0x2e+month),\n"
            " * the QuickNote hint, and the navigation screen's text.\n"
            " *\n"
            " * The tables hold ABSOLUTE original-image addresses.  Our build relocates\n"
            " * every target, so each word is taken from the LINKER, exactly as batch 5's\n"
            " * ptr_record objects do (recon/emulator/reports/pointer_rebind.md).  No raw\n"
            " * absolute address is stored.  Byte equality with app_update.bin therefore\n"
            " * holds MODULO RELOCATION for the eight tables and EXACTLY for the two data\n"
            " * objects below.\n"
            " */\n\n"
        )
        fh.write(
            "/* 0x%05x, %d B -- the empty localized string (a single NUL). */\n"
            "const unsigned char g1_ro_a8ea0[%d] __asm__(\"rodata_a8ea0\") = { 0x00, };\n\n"
            % (EMPTY_VA, EMPTY_LEN, EMPTY_LEN)
        )
        fh.write(
            "/* 0x%05x, %d B -- the localized string POOL [0x%05x, 0x%05x), byte-exact.\n"
            " * gen_app_string_rodata.py had emitted only its FIRST string, an 11-byte\n"
            " * \"ERR_STRING\" stub, because the pin named a printable C string; the other\n"
            " * 128 strings the eight tables point at were emitted nowhere at all.\n"
            " */\n"
            "const unsigned char g1_ro_bb220[%d] __asm__(\"rodata_bb220\") = {\n%s\n};\n\n"
            % (POOL_VA, POOL_LEN, POOL_VA, POOL_VA + POOL_LEN, POOL_LEN, hexrows(pool))
        )
        for va in TABLES:
            ws = words[va]
            fh.write("/* 0x%05x, %d B -- localized string table, %d relocated entries. */\n"
                     % (va, TABLE_ENTRIES * 4, TABLE_ENTRIES))
            fh.write("const unsigned long g1_ro_%x[%d] __asm__(\"rodata_%x\") = {\n"
                     % (va, TABLE_ENTRIES, va))
            for i, w in enumerate(ws):
                if w == 0:
                    fh.write("\t0,\t\t\t/* [0x%02x] NULL */\n" % i)
                elif w == EMPTY_VA:
                    fh.write("\t(unsigned long)g1_ro_a8ea0,\t/* [0x%02x] was 0x%05x -> \"\" */\n"
                             % (i, w))
                else:
                    off = w - POOL_VA
                    txt = pool[off:pool.find(b"\x00", off)]
                    try:
                        shown = txt.decode("utf-8")
                    except UnicodeDecodeError:
                        shown = txt.decode("latin-1")
                    shown = shown.replace("\\", "\\\\").replace("*/", "* /")
                    if len(shown) > 46:
                        shown = shown[:46] + "..."
                    fh.write("\t(unsigned long)(g1_ro_bb220 + 0x%04x),\t/* [0x%02x] was 0x%05x -> \"%s\" */\n"
                             % (off, i, w, shown))
            fh.write("};\n\n")

    # ---- file 3: the glyph blob, SPLIT so the demo image is not carried ---
    lut = extract.read(LUT_VA, LUT_LEN)
    glyphs = extract.read(GLYPH_VA, GLYPH_LEN)
    p3 = os.path.join(REPO, "recon/application/app/src/g1_app_glyph_bitmap_rodata.c")
    with open(p3, "w") as fh:
        fh.write(
            "/* GENERATED by recon/application/gen_app_localized_rodata.py -- DO NOT EDIT.\n"
            " *\n"
            " * P4 iteration 36 SPLITS the 59,944-byte run [0xd753a, 0xe5f62) that\n"
            " * recon/application/rodata/g1_app_rodata_02.c owned as one object\n"
            " * `rodata_d753a`, because the shipped image is 977,805 B against a 982,528 B\n"
            " * partition and the fade-mask atlas had to fit.  The run is three\n"
            " * independent resources:\n"
            " *\n"
            " *   [0xd753a, 0xd793a)  1,024 B  256 x uint32 nibble-expansion LUT,\n"
            " *                                read by expand_bytes_via_lut32.   EMITTED\n"
            " *   [0xd793a, 0xe123a) 39,680 B  the low-battery DEMO IMAGE bitmap.\n"
            " *                                Its ONLY reader is update_demo_image_display,\n"
            " *                                through demo_image_get_position(0), i.e.\n"
            " *                                rodata_0x8ac20[0] = 0xd793a, and\n"
            " *                                ui_refalsh_warp only reaches it when\n"
            " *                                is_battery_critical() == 1.  Neither display\n"
            " *                                parity phase enters that path.    WITHHELD\n"
            " *   [0xe123a, 0xe5f62) 19,752 B  the icon bitmaps rodata_e123a reads plus the\n"
            " *                                three glyph bitmap runs rodata_e17da (font\n"
            " *                                style 3), rodata_e4408 and rodata_e5248\n"
            " *                                (the clock digit families).          EMITTED\n"
            " *\n"
            " * rodata_0x8ac20[0] keeps its shipped absolute word 0x000d793a exactly as it\n"
            " * is today; withholding the demo image changes nothing about it.  The three\n"
            " * interior pins are re-expressed on rodata_e123a in g1_app_globals.ld.\n"
            " * Bytes from app_update.bin through tools/extract.py.\n"
            " */\n"
        )
        fh.write("const unsigned char g1_ro_d753a[%d] __asm__(\"rodata_d753a\") = {\n%s\n};\n\n"
                 % (LUT_LEN, hexrows(lut)))
        fh.write("const unsigned char g1_ro_e123a[%d] __asm__(\"rodata_e123a\") = {\n%s\n};\n"
                 % (GLYPH_LEN, hexrows(glyphs)))

    print("wrote %s (%d B object)" % (p1, ATLAS_LEN))
    print("wrote %s (%d B LUT + %d B glyph/icon run; %d B demo image withheld)"
          % (p3, LUT_LEN, GLYPH_LEN, GLYPH_VA - (LUT_VA + LUT_LEN)))
    print("wrote %s (%d B pool + %d tables x %d B + %d B empty)"
          % (p2, POOL_LEN, len(TABLES), TABLE_ENTRIES * 4, EMPTY_LEN))
    print("distinct string targets: %d (all inside the pool bar the empty string)" % len(targets))


if __name__ == "__main__":
    main()
