#!/usr/bin/env python3
"""Source-level raw CPUAPP FLASH-literal checker (P4 iteration 49).

WHY THIS EXISTS
---------------
Two gates already score raw absolute addresses and neither can see this class:

  * `check_ram_pin_collisions.py` scores the LINKER pins
    (`PROVIDE(name = 0x…)`) of both cores inside the RAM window;
  * `check_net_raw_literals.py` scores `0x21xxxxxx` **net-core RAM** addresses
    written directly into a C body.

Nothing scored an **app-core FLASH** address written into a C body.  Measured
consequence (`recon/analysis/boot_cost_per_byte.md`): four `log_message()` call
sites pass a raw ORIGINAL-image `.rodata` address as their *format pointer*.
In the shipped image those addresses hold real format strings; in our relinked
image they hold unrelated bytes, so `printf` walks to the next NUL and the
console output — and with it the whole boot-path timing the phase criterion
gates on — becomes a function of link layout.  Suppressing exactly those four
calls collapsed a 1.140 ms / 420-byte boot-offset spread to 0.000 ms with the
image byte-untouched.

WHAT IT SCORES
--------------
Every integer constant in a repository reconstruction source whose value falls
in the ORIGINAL app image's flash window `[0xC200, 0xC200 + len(app_update.bin)
- 512)`, classified by **what the value is used for**, not by its numeric range:

  pointer      the constant is (or feeds) a cast to a pointer type, i.e. the
               address is dereferenced.  Always a defect: our image is
               relocated, so the address names unrelated bytes.
  magic        the constant is a direct operand of a comparison or a `case`
               label -- compared, never dereferenced.  Iteration 5 established
               this class with the retained-block validity magic `0x12345678`.
  unknown      anything else (call argument, assignment, initialiser,
               arithmetic).  A call argument is exactly the shape of the four
               proven-live defects, so `unknown` is NOT assumed benign.

FAIL-CLOSED
-----------
`magic` passes.  `pointer` and `unknown` FAIL unless the value carries a
reviewed entry in the ledger (`--ledger`, default
`recon/emulator/scripts/app_flash_literal_ledger.json`) with a non-empty
`reason`; and a ledger entry may only cover a `pointer` use when its
disposition is explicitly `pointer_reviewed`.  A value the scanner cannot
classify therefore fails, and so does a value nobody has reviewed.

NOT DEFEATABLE THE WAY SIX PRIOR SCANNERS IN THIS PROJECT WERE
--------------------------------------------------------------
Every prior scanner here was beaten by text-anchored parsing -- a trailing
`/* memset */` comment, `-aux-info` lines ending `/* (params) */`, a
parameter-list struct-tag scope, a comma-separated declarator list.  This one
never matches against a line, never anchors at end of line and never
regex-scans the raw file.  It runs a real C tokenizer (`ctokenize` below) that
consumes comments, string literals and character constants as it goes, and
classifies from the resulting TOKEN stream with a paren stack.  Consequences
that are asserted by the shipped controls in
`recon/refactor/test_app_flash_literals.py`:

  * a literal inside a comment or a string is not a token and is never scored;
  * `0x00099919` and the short spelling `0x99919` and `0x99919UL` are the same
    value (the previous survey regex `0x000[9a-e][0-9a-f]{4}` saw only the
    first, which is why its "117 distinct" was NOT an upper bound);
  * `0x999190` is a different number and does not match either;
  * a trailing comment, a comma-declarator list or a macro cannot hide a use.

Usage:
    check_app_flash_literals.py --tree DIR [--tree DIR ...] [--json OUT]
    check_app_flash_literals.py --build BUILDDIR [--json OUT]     (preprocessed)

`--tree` tokenizes the reconstruction sources directly (works on a stage tree
with no build).  `--build` re-runs every repository translation unit of an
existing build through the same compiler and flags with `-E`, which is exact
with respect to `#if` branches and macro expansion; it is the stronger mode and
requires `compile_commands.json`.  Preprocessing is not a nicety: a
`#define PTR 0x8278b` used as `(void *)PTR` reads as `unknown` in the raw tree
and as `pointer` after `-E`, and 30 values in the base build are only visible
that way.

SCOPE.  The authoritative scopes are the two the ladder cares about -- a linked
build (`--build`) and a stage tree (`--tree <stage>/tree/recon`).  Pointing it
at the whole readable corpus (`recon/named`, `recon/readable_sources`, ...)
scores ~2,200 values, because those trees hold every reconstruction including
the ~600 the adoption manifest excludes from the link; those are real members
of the class but nothing links them, and they are NOT in the ledger.
Generated byte-exact data TUs and CPUNET sources are excluded by construction
(see `is_generated_data_tu` / `is_net_source`).

Exit status is 0 when every scored use is `magic` or carries a reviewed ledger
entry that covers it.
"""
import argparse
import json
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
APP_BIN = os.path.join(REPO, "app_update.bin")
APP_LINK_BASE = 0xC200          # tools/extract.py: image linked here
APP_HDR = 512                   # MCUboot header; file offset of the link base
# End of the last shipped CPUAPP function body: max(entry + size) over the
# 2,417 functions of the Ghidra catalogue (`classified.json`).  Re-derive with
#   json.load(open(classified.json))["functions"] -> max(f["entry"]+f["size"])
# It is the boundary between the code window and the read-only-data window and
# it is a MEASUREMENT, not a taste judgement.
APP_TEXT_END = 0x88846
DEFAULT_LEDGER = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "app_flash_literal_ledger.json")


def image_window():
    """[lo, hi) of the ORIGINAL app image in its own link coordinates."""
    size = os.path.getsize(APP_BIN)
    return APP_LINK_BASE, APP_LINK_BASE + size - APP_HDR


def in_scope(use, lo, hi, data_lo):
    """Which uses this gate scores.

    Two tiers, because the two windows carry different amounts of information:

      * `[data_lo, hi)` -- the shipped image's READ-ONLY DATA region, past the
        end of the last function body.  A literal there is an address or
        nothing; EVERY use is scored, and `unknown` fails closed.  The four
        proven-live defects (`0x99919`, `0x993c9`, `0x9943c`, `0x99476`) are
        call arguments, i.e. `unknown`, so this tier must not be relaxed.
      * `[lo, data_lo)` -- the CODE region.  Ordinary program constants
        (bit masks, sizes, HCI opcodes, baud rates) live in the same numeric
        range, so only a use the scanner can PROVE is a dereference is scored.
        A code address that is merely computed and never dereferenced cannot
        move anything at run time.
    """
    v = use["value"]
    if data_lo <= v < hi:
        return True
    return lo <= v < data_lo and use["class"] == "pointer"


# --------------------------------------------------------------------------
# A real C tokenizer.  Comments, string literals and character constants are
# consumed by the scanner, so nothing that lives inside one can ever be scored,
# and nothing outside one can be hidden by a trailing comment.
# --------------------------------------------------------------------------
PUNCT = sorted([
    "...", "<<=", ">>=", "->", "++", "--", "<<", ">>", "<=", ">=",
    "==", "!=", "&&", "||", "*=", "/=", "%=", "+=", "-=", "&=", "^=", "|=",
    "##",
    "[", "]", "(", ")", "{", "}", ".", "&", "*", "+", "-", "~", "!", "/",
    "%", "<", ">", "^", "|", "?", ":", ";", "=", ",", "#",
], key=len, reverse=True)

_ID = re.compile(r"[A-Za-z_$][A-Za-z0-9_$]*")
# C preprocessing-number: this is what makes `0x99919UL` ONE token and
# `0x999190` a DIFFERENT token rather than a prefix match of `0x99919`.
_NUM = re.compile(r"\.?[0-9](?:[0-9a-zA-Z_.]|[eEpP][+-])*")
_LINEMARK = re.compile(r'^#\s*(?:line\s+)?(\d+)\s+"((?:[^"\\]|\\.)*)"')
_INT_SUFFIX = re.compile(r"(?:[uU](?:l{1,2}|L{1,2})?|(?:l{1,2}|L{1,2})[uU]?)$")


class Tok(object):
    __slots__ = ("kind", "text", "file", "line", "value", "pos", "end")

    def __init__(self, kind, text, file, line, value=None, pos=-1, end=-1):
        self.kind, self.text, self.file, self.line, self.value = \
            kind, text, file, line, value
        self.pos, self.end = pos, end

    def __repr__(self):
        return "<%s %r %s:%d>" % (self.kind, self.text, self.file, self.line)


def int_value(text):
    """Integer value of a pp-number token, or None when it is not an integer."""
    body = _INT_SUFFIX.sub("", text)
    try:
        low = body[:2].lower()
        if low == "0x":
            return int(body, 16)
        if low == "0b":
            return int(body, 2)
        if body.startswith("0") and len(body) > 1:
            return int(body, 8)
        return int(body, 10)
    except ValueError:
        return None


def ctokenize(text, filename="<src>", track_linemarks=False):
    """Yield Tok.  kinds: id, num, str, chr, punct."""
    i, n, line = 0, len(text), 1
    cur_file, at_line_start = filename, True
    while i < n:
        c = text[i]
        if c == "\n":
            line += 1
            i += 1
            at_line_start = True
            continue
        if c in " \t\r\f\v":
            i += 1
            continue
        if c == "\\" and text.startswith("\\\n", i):
            i += 2
            line += 1
            continue
        if text.startswith("/*", i):
            end = text.find("*/", i + 2)
            end = n if end < 0 else end + 2
            line += text.count("\n", i, end)
            i, at_line_start = end, False
            continue
        if text.startswith("//", i):
            end = text.find("\n", i)
            i = n if end < 0 else end
            continue
        if c == "#" and at_line_start and track_linemarks:
            end = text.find("\n", i)
            end = n if end < 0 else end
            m = _LINEMARK.match(text[i:end])
            if m:
                line, cur_file = int(m.group(1)) - 1, m.group(2)
                i = end
                continue
        at_line_start = False
        j = i
        if c in "LuU":                       # encoding-prefixed literal
            k = i + 1
            if text.startswith("8", k):
                k += 1
            if k < n and text[k] in "\"'":
                j = k
        if text[j:j + 1] in ('"', "'"):
            q, k = text[j], j + 1
            while k < n:
                if text[k] == "\\":
                    k += 2
                    continue
                if text[k] == q:
                    k += 1
                    break
                if text[k] == "\n":
                    break
                k += 1
            raw = text[i:k]
            yield Tok("str" if q == '"' else "chr", raw, cur_file, line,
                      None, i, k)
            line += raw.count("\n")
            i = k
            continue
        m = _NUM.match(text, i)
        if m:
            yield Tok("num", m.group(0), cur_file, line,
                      int_value(m.group(0)), m.start(), m.end())
            i = m.end()
            continue
        m = _ID.match(text, i)
        if m:
            yield Tok("id", m.group(0), cur_file, line, None,
                      m.start(), m.end())
            i = m.end()
            continue
        for p in PUNCT:
            if text.startswith(p, i):
                yield Tok("punct", p, cur_file, line, None, i, i + len(p))
                i += len(p)
                break
        else:
            i += 1


# --------------------------------------------------------------------------
# Use classification, from the token stream
# --------------------------------------------------------------------------
CMP_OPS = {"==", "!=", "<", ">", "<=", ">="}
TYPE_HEAD = {
    "void", "char", "short", "int", "long", "float", "double", "signed",
    "unsigned", "const", "volatile", "struct", "union", "enum", "_Bool",
}


def _matching_open(toks, close_idx):
    depth = 0
    i = close_idx
    while i >= 0:
        t = toks[i]
        if t.kind == "punct":
            if t.text == ")":
                depth += 1
            elif t.text == "(":
                depth -= 1
                if depth == 0:
                    return i
        i -= 1
    return -1


def _is_pointer_cast_close(toks, close_idx):
    """True when toks[close_idx] is the ')' of a cast to a POINTER type."""
    if close_idx < 2 or toks[close_idx].text != ")":
        return False
    if toks[close_idx - 1].text != "*":
        return False
    open_idx = _matching_open(toks, close_idx)
    if open_idx < 0 or open_idx + 1 >= close_idx:
        return False
    head = toks[open_idx + 1]
    if head.kind != "id":
        return False
    if head.text in TYPE_HEAD:
        return True
    # a typedef name: accept when the whole group is <id> <*>+ only, which is
    # the shape a cast has and a multiplication expression does not.
    body = toks[open_idx + 1:close_idx]
    return all(t.text == "*" for t in body[1:]) and len(body) >= 2


def classify_uses(toks, lo, hi):
    """-> [{value,line,file,class,ctx}] for every in-window integer constant."""
    toks = list(toks)
    out = []
    # paren stack: index of each currently-open '('
    stack, opens = [], [-1] * len(toks)
    for i, t in enumerate(toks):
        if t.kind == "punct":
            if t.text == "(":
                stack.append(i)
            elif t.text == ")" and stack:
                stack.pop()
        opens[i] = stack[-1] if stack else -1

    # a second pass needs the enclosing-open index computed BEFORE the token
    # itself is pushed/popped, which the loop above already gives for numbers.
    for i, t in enumerate(toks):
        if t.kind != "num" or t.value is None:
            continue
        if not (lo <= t.value < hi):
            continue
        prev = toks[i - 1] if i else None
        nxt = toks[i + 1] if i + 1 < len(toks) else None
        cls, why = "unknown", ""

        # --- pointer: a cast to a pointer type, directly or through parens ---
        if prev is not None and _is_pointer_cast_close(toks, i - 1):
            cls, why = "pointer", "cast to pointer type"
        else:
            j = opens[i]
            seen = 0
            while j > 0 and seen < 4:
                if _is_pointer_cast_close(toks, j - 1):
                    cls, why = "pointer", "inside a pointer-cast operand"
                    break
                j = opens[j]
                seen += 1

        if cls == "unknown":
            # --- magic: a direct operand of a comparison, or a case label ---
            if (prev is not None and prev.kind == "punct" and prev.text in CMP_OPS) or \
               (nxt is not None and nxt.kind == "punct" and nxt.text in CMP_OPS):
                cls, why = "magic", "direct operand of a comparison"
            elif prev is not None and prev.kind == "id" and prev.text == "case":
                cls, why = "magic", "switch case label"
            else:
                j = opens[i]
                callee = None
                if j > 0 and toks[j - 1].kind == "id" and \
                        toks[j - 1].text not in TYPE_HEAD:
                    callee = toks[j - 1].text
                if callee:
                    why = "argument of %s()" % callee
                elif prev is not None and prev.text == "=":
                    why = "assignment"
                elif prev is not None and prev.text in ("{", ","):
                    why = "initialiser element"
                else:
                    why = "unclassified expression operand"

        lhs = " ".join(x.text for x in toks[max(0, i - 6):i])
        rhs = " ".join(x.text for x in toks[i + 1:i + 5])
        out.append({"value": t.value, "line": t.line, "file": t.file,
                    "pos": t.pos, "end": t.end, "class": cls, "why": why,
                    "ctx": ("%s [%s] %s" % (lhs, t.text, rhs)).strip()})
    return out


# --------------------------------------------------------------------------
# Inputs
# --------------------------------------------------------------------------
SRC_EXT = (".c", ".h", ".cpp", ".cc", ".hpp", ".inc")

# Translation units whose CONTENT is byte-exact image data rather than
# hand-written code.  An integer in one of these is a shipped BYTE, not a
# source-level address reference: `recon/data/**` and `recon/application/
# rodata/**` are emitted by `gen_app_*_rodata.py` / `make_blobs.py` straight
# out of `app_update.bin`, and `tools/verify_data.py` byte-compares every one
# of them against the image (995/995 files, 56,279/56,279 B at the time of
# writing).  Scoring them would flag the image's own float bit-patterns and
# stored pointer words, which is a category error -- the defect this gate
# exists for is a raw address a HUMAN or a decompiler wrote into a body.
DATA_TU_DIRS = ("/recon/data/", "/recon/application/rodata/",
                "/recon/blobs/", "/recon/net/data/")
DATA_TU_NAMES = re.compile(
    r"^(?:rodata_(?:0x)?[0-9a-fA-F]+\.c"
    r"|g1_app_(?:[a-z_]*_)?rodata(?:_\d+)?\.c"
    r"|g1_app_data_image\.c"
    r"|g1_net_[a-z_]*data[a-z_]*\.c)$")


# CPUNET sources.  This gate is the APP-core counterpart of
# `check_net_raw_literals.py`; the net core links at 0x01008800 in a different
# address space, so an app-flash-window integer in a net body is an ordinary
# constant and scoring it would be a category error.
NET_DIRS = ("/recon/net/", "/recon/symbolized/net/", "/recon/application/net/",
            "/recon/blobs/net/")


def is_net_source(path):
    ap = os.path.abspath(path).replace(os.sep, "/")
    return any(d in ap for d in NET_DIRS)


def is_generated_data_tu(path):
    ap = os.path.abspath(path).replace(os.sep, "/")
    if any(d in ap for d in DATA_TU_DIRS):
        return True
    return bool(DATA_TU_NAMES.match(os.path.basename(ap)))


def is_recon_source(path, repo):
    if not path:
        return False
    ap = os.path.abspath(path)
    if is_generated_data_tu(ap) or is_net_source(ap):
        return False
    # inside a stage tree the repository sources live under <stage>/tree/recon/
    return (os.sep + "recon" + os.sep) in ap + os.sep or \
        ap.startswith(os.path.join(repo, "recon") + os.sep)


def scan_tree(root, lo, hi):
    uses = []
    for dp, dn, fn in os.walk(root):
        dn[:] = [d for d in dn if d not in (".git", "__pycache__", "build")]
        for f in sorted(fn):
            if not f.endswith(SRC_EXT):
                continue
            p = os.path.join(dp, f)
            if is_generated_data_tu(p) or is_net_source(p):
                continue
            try:
                with open(p, encoding="utf-8", errors="replace") as fh:
                    txt = fh.read()
            except OSError:
                continue
            for u in classify_uses(ctokenize(txt, p), lo, hi):
                u["file"] = p
                uses.append(u)
    return uses


def _preprocess(entry, repo, lo, hi):
    src = entry.get("file")
    if not is_recon_source(src, repo):
        return []
    args = entry.get("arguments")
    if args is None:
        cmd = entry.get("command")
        args = cmd.split() if cmd else None
    if not args:
        return []
    out, skip = [], False
    for a in args:
        if skip:
            skip = False
            continue
        if a == "-o":
            skip = True
            continue
        if a in ("-c", "-MD", "-MMD"):
            continue
        if a in ("-MF", "-MT", "-MQ"):
            skip = True
            continue
        if a.startswith("-o") and len(a) > 2:
            continue
        out.append(a)
    out.append("-E")
    proc = subprocess.run(out, cwd=entry.get("directory", repo),
                          capture_output=True, text=True)
    if proc.returncode != 0:
        return [{"value": None, "file": src, "line": 0, "class": "preprocess_failed",
                 "why": (proc.stderr.strip().splitlines() or ["?"])[-1], "ctx": ""}]
    res = []
    for u in classify_uses(ctokenize(proc.stdout, src, track_linemarks=True), lo, hi):
        if is_recon_source(u["file"], repo):
            res.append(u)
    return res


def scan_build(build, repo, lo, hi, jobs=8):
    cc = os.path.join(build, "compile_commands.json")
    if not os.path.exists(cc):
        print("missing %s" % cc, file=sys.stderr)
        return None
    entries = [e for e in json.load(open(cc)) if is_recon_source(e.get("file"), repo)]
    uses = []
    with ThreadPoolExecutor(max_workers=jobs) as ex:
        for r in ex.map(lambda e: _preprocess(e, repo, lo, hi), entries):
            uses.extend(r)
    return uses


# --------------------------------------------------------------------------
def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--tree", action="append", default=[])
    ap.add_argument("--build", default=None)
    ap.add_argument("--repo", default=REPO)
    ap.add_argument("--ledger", default=DEFAULT_LEDGER)
    ap.add_argument("--json", dest="json_out")
    ap.add_argument("--jobs", type=int, default=8)
    ap.add_argument("--max-print", type=int, default=40)
    ap.add_argument("--lo", type=lambda s: int(s, 0), default=None)
    ap.add_argument("--hi", type=lambda s: int(s, 0), default=None)
    ap.add_argument("--data-lo", type=lambda s: int(s, 0), default=APP_TEXT_END)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    lo, hi = image_window()
    if args.lo is not None:
        lo = args.lo
    if args.hi is not None:
        hi = args.hi
    data_lo = args.data_lo
    repo = os.path.abspath(args.repo)

    uses = []
    if args.build:
        r = scan_build(args.build, repo, lo, hi, args.jobs)
        if r is None:
            return 2
        uses.extend(r)
    for t in args.tree:
        uses.extend(scan_tree(t, lo, hi))
    if not args.tree and not args.build:
        ap.error("give --tree and/or --build")

    ledger = {}
    if os.path.exists(args.ledger):
        with open(args.ledger) as fh:
            raw = json.load(fh)
        for k, v in raw.get("entries", raw).items():
            try:
                ledger[int(k, 16) if isinstance(k, str) else int(k)] = v
            except ValueError:
                pass

    failed_pp = [u for u in uses if u["class"] == "preprocess_failed"]
    scanned = [u for u in uses if u["class"] != "preprocess_failed"]
    uses = [u for u in scanned if in_scope(u, lo, hi, data_lo)]

    by_value = {}
    for u in uses:
        by_value.setdefault(u["value"], []).append(u)

    unreviewed, pointer_unreviewed, covered, magic = [], [], [], []
    for v, us in sorted(by_value.items()):
        entry = ledger.get(v)
        classes = {u["class"] for u in us}
        if classes == {"magic"}:
            magic.append((v, us))
            continue
        ok = bool(entry) and bool(str(entry.get("reason", "")).strip())
        if "pointer" in classes and (not entry or
                                     entry.get("disposition") != "pointer_reviewed"):
            pointer_unreviewed.append((v, us, entry))
        elif ok:
            covered.append((v, us))
        else:
            unreviewed.append((v, us, entry))

    summary = {
        "window": [hex(lo), hex(hi)],
        "rodata_window": [hex(data_lo), hex(hi)],
        "in_window_uses_seen": len(scanned),
        "trees": args.tree,
        "build": args.build,
        "translation_units_failed_to_preprocess": len(failed_pp),
        "distinct_values": len(by_value),
        "occurrences": len(uses),
        "files": len({u["file"] for u in uses}),
        "values_all_uses_magic": len(magic),
        "values_reviewed_in_ledger": len(covered),
        "values_dereferenced_and_unreviewed": len(pointer_unreviewed),
        "values_unclassified_and_unreviewed": len(unreviewed),
    }
    if not args.quiet:
        for k, v in summary.items():
            print("%-45s %s" % (k, v))

    def show(title, rows):
        if not rows or args.quiet:
            return
        print()
        print("=== %s (%d) ===" % (title, len(rows)))
        for v, us, _e in rows[:args.max_print]:
            u = us[0]
            print("0x%08x  %-9s %-34s %s:%d  %s" % (
                v, u["class"], u["why"],
                os.path.basename(u["file"]), u["line"], u["ctx"][:70]))
        if len(rows) > args.max_print:
            print("... %d more" % (len(rows) - args.max_print))

    show("DEREFERENCED app-core flash addresses, UNREVIEWED -- DEFECT",
         pointer_unreviewed)
    show("UNCLASSIFIED app-core flash literals, UNREVIEWED -- fail closed",
         unreviewed)

    for u in failed_pp:
        print("PREPROCESS FAILED %s: %s" % (u["file"], u["why"]), file=sys.stderr)

    if args.json_out:
        json.dump({"summary": summary,
                   "dereferenced_unreviewed": [
                       {"value": hex(v), "uses": us} for v, us, _ in pointer_unreviewed],
                   "unclassified_unreviewed": [
                       {"value": hex(v), "uses": us} for v, us, _ in unreviewed],
                   "reviewed": [{"value": hex(v), "uses": us} for v, us in covered],
                   "magic": [{"value": hex(v), "uses": us} for v, us in magic]},
                  open(args.json_out, "w"), indent=1)

    bad = len(pointer_unreviewed) + len(unreviewed) + len(failed_pp)
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
