/*
 * Cohesive translation unit for the `lib' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 2 functions below were 2 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   gatt_mult_notify_dispatch.c
 *   gatt_disconnected.c
 */

/* File-scope forward declarations for every struct/union tag this
 * unit names.  Without them a tag whose only appearance in a member
 * is inside a parameter list has PARAMETER-LIST scope, so two
 * textually IDENTICAL declarations in two members declare two
 * different incomplete types and the second is a conflicting
 * redeclaration (C11 6.2.1p7).  Incomplete-type forward
 * declarations emit no code. */
struct cursor_5c5f0;
struct handler_5c5f0;
/* ---- gatt_mult_notify_dispatch.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_0005c5f0 @ 0x0005c5f0
 * public-name: gatt_mult_notify_dispatch
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   gatt_find_conn_in_known_table            <= FUN_00059c70 @ 0x00059c70
 *   bt_gatt_unsubscribe                      <= FUN_0005c4f0 @ 0x0005c4f0
 *   gatt_mult_notify_dispatch                <= FUN_0005c5f0 @ 0x0005c5f0
 *   net_buf_simple_pull_5f594                <= FUN_0005f594 @ 0x0005f594
 *   log_msg_create_3arg                      <= FUN_00082a42 @ 0x00082a42
 *   net_buf_simple_init_with_data            <= FUN_000836ec @ 0x000836ec
 * address symbols (name @ address):
 *   rodata_88128                             @ 0x00088128
 *   rodata_f4d6f                             @ 0x000f4d6f   [INLINED -- G6 literal batch]
 */
/* Full reconstruction FUN_0005c5f0 @ 0x5c5f0, exact extent 206 bytes. */
#include <stdint.h>

extern unsigned char* gatt_find_conn_in_known_table(int);
extern void net_buf_simple_init_with_data(void *, const void *, uint32_t);
extern void *net_buf_simple_pull_5f594(void *, uint32_t);
extern void log_msg_create_3arg(uintptr_t, uint32_t, const void *);
extern void bt_gatt_unsubscribe(void *, void *);

struct cursor_5c5f0 { uint8_t opaque[4]; uint16_t remaining; };
struct handler_5c5f0 {
    int (*invoke)(void *, struct handler_5c5f0 *, const void *, uint32_t);
    uint8_t pad04[8];
    uint16_t type;
    uint8_t pad0e[4];
    uint8_t minimum;
    uint8_t pad13[5];
    struct handler_5c5f0 *next;
};

static void gatt_mult_notify_dispatch(uint8_t *context, const void *data, uint32_t length)
{
    uint8_t *group = gatt_find_conn_in_known_table(context);
    struct cursor_5c5f0 cursor;
    if (group == 0)
        return;
    net_buf_simple_init_with_data(&cursor, data, length);
    while (cursor.remaining > 4) {
        uint16_t *header = net_buf_simple_pull_5f594(&cursor, 4);
        uint16_t type = header[0], payload_length = header[1];
        if (cursor.remaining < payload_length) {
            struct { uint32_t count; uintptr_t message; uint32_t length; uint32_t total; } log =
                { 4, ((unsigned long)"Invalid data len %u > %u") /*=0xf4d6f*/, payload_length, length };
            log_msg_create_3arg(((unsigned long)&rodata_88128) /*=0x88128*/, 0x2040, &log);
            return;
        }
        struct handler_5c5f0 *node = *(struct handler_5c5f0 **)(group + 8);
        if (node != 0) {
            struct handler_5c5f0 *next = node->next;
            if (next != 0) next = (void *)((uint8_t *)next - 24);
            node = (void *)((uint8_t *)node - 24);
            for (;;) {
                if (node->type == type && node->minimum <= context[9] &&
                    node->invoke(context, node, header + 2, payload_length) == 0)
                    bt_gatt_unsubscribe(context, node);
                if (next == 0) break;
                node = next;
                next = node->next;
                if (next != 0) next = (void *)((uint8_t *)next - 24);
            }
        }
        net_buf_simple_pull_5f594(&cursor, payload_length);
    }
}

/* ---- gatt_disconnected.c ---- */
/* readable reconstruction; identity: FUN_0005c87c @ 0x0005c87c
 * public-name: gatt_disconnected
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   find_cf_cfg_by_addr                      <= FUN_00059b5c @ 0x00059b5c
 *   bt_gatt_store_cf                         <= FUN_0005a8bc @ 0x0005a8bc
 *   bt_gatt_store_ccc                        <= FUN_0005c80c @ 0x0005c80c
 *   gatt_disconnected                        <= FUN_0005c87c @ 0x0005c87c
 *   bt_addr_le_is_bonded                     <= FUN_00080f92 @ 0x00080f92
 *   bt_addr_le_copy_828da                    <= FUN_000828da @ 0x000828da
 *   bt_gatt_foreach_attr_0                   <= FUN_00082c9c @ 0x00082c9c
 * address symbols (name @ address):
 *   rodata_5a2fd                             @ 0x0005a2fd
 */
/* Reconstructed FUN_0005c87c @ 0x5c87c  (parity: 300/300 trials, PROVEN) */
extern int find_cf_cfg_by_addr(int,int);
extern void bt_gatt_store_cf(unsigned int, unsigned int);
extern int bt_gatt_store_ccc(unsigned int, unsigned int);
extern int bt_addr_le_is_bonded(unsigned char, const void*);
extern void bt_addr_le_copy_828da(void*, const void*);
extern void bt_gatt_foreach_attr_0(unsigned short, unsigned short, void*, void*);
void gatt_disconnected(int param_1, uint32_t param_2, uint32_t param_3){
  int iVar3 = param_1 + 0x90;
  uint32_t local[2];
  local[0] = param_2;
  local[1] = param_3;
  int iVar1 = bt_addr_le_is_bonded(*(volatile uint8_t *)(param_1+8), iVar3);
  bt_gatt_foreach_attr_0(1, 0xffff, ((unsigned long)&rodata_5a2fd) /*=0x5a2fd*/, local);
  if(iVar1 != 0){
    bt_gatt_store_ccc(*(volatile uint8_t *)(param_1+8), iVar3);
  }
  int iVar2 = find_cf_cfg_by_addr(*(volatile uint8_t *)(param_1+8), param_2);
  if(iVar2 != 0){
    bt_addr_le_copy_828da(iVar2+1, param_3);
    if(iVar1 != 0){
      bt_gatt_store_cf(*(volatile uint8_t *)(param_1+8), iVar3);
    }
  }
}

