/*
 * Call-cohesive translation unit for the `lib' module.
 *
 * GENERATED by recon/refactor/transforms/t09_call_cohesion.py.  Do
 * not edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 2 translation units below were grouped because they CALL ONE
 * ANOTHER, not because they were adjacent in the generated source
 * list.  Each member's text is reproduced VERBATIM.  Every member was
 * checked pairwise against every other member already in this unit by
 * stage 04's seven refusal rules, unchanged: no symbol is declared
 * here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct
 * tag or enum constant of one member is visible to a member that
 * names it.
 *
 * members, in generated-source-list order:
 *   g1_lib_71.c
 *   cbor_decode_precheck.c
 *
 * call edges inside this unit (caller -> callee): 1
 *   cbor_decode_precheck.c -> g1_lib_71.c
 */
/* ================================================================ */
/* member unit: g1_lib_71.c */
/* ================================================================ */
/*
 * Cohesive translation unit for the `lib' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 2 functions below were 2 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   rpmsg_virtio_get_tx_buffer_wait.c
 *   cbor_decode_is_exhausted.c
 */
/* ---- rpmsg_virtio_get_tx_buffer_wait.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_00085b0c @ 0x00085b0c
 * public-name: rpmsg_virtio_get_tx_buffer_wait
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   k_sleep                                  <= FUN_00074844 @ 0x00074844
 *   virtqueue_get_buffer                     <= FUN_00085734 @ 0x00085734
 *   mutex_lock_wait_forever_dup              <= FUN_000859b6 @ 0x000859b6
 *   rpmsg_virtio_shm_pool_get_buffer         <= FUN_00085aee @ 0x00085aee
 *   rpmsg_virtio_get_tx_buffer_wait          <= FUN_00085b0c @ 0x00085b0c
 */
/* Reconstructed FUN_00085b0c @ 0x85b0c  (parity: 300/300 trials, PROVEN) */
#include <stdint.h>
#include "g1_lib.h"
extern int32_t k_sleep(k_timeout_t);
extern int* virtqueue_get_buffer(uint32_t,int*,void*,uint32_t,int);
extern void mutex_lock_wait_forever_dup(int);
extern unsigned long process_sync_buffer(unsigned int, ...);
typedef int (*fp0)(void);
int* rpmsg_virtio_get_tx_buffer_wait(int param_1, int* param_2, int param_3){
    int iVar5=param_1;
    uint32_t uStack_24=(uint32_t)param_2;
    int iVar1=(*(volatile fp0 *)(*(volatile int *)(*(volatile int *)(param_1+0xa0)+0x20)+8))();
    if((iVar1<<0x1d)>=0) return 0;
    if(param_3!=0) param_3=15000;
    int addr58=param_1+0x58;
    int iVar4; int* piVar3;
    while(1){
        mutex_lock_wait_forever_dup(addr58);
        piVar3=*(int* volatile*)(param_1+0xb4);
        iVar4=*(volatile int *)(*(volatile int *)(param_1+0xa0)+0x18);
        if(piVar3!=(int*)(param_1+0xb4) && piVar3!=0) break;
        if(iVar4==0){
            piVar3=virtqueue_get_buffer(*(volatile uint32_t *)(param_1+0xa8),param_2,(uint8_t*)&uStack_24+2,*(volatile uint32_t *)(param_1+0xa0),iVar5);
            if(piVar3!=0) goto L6a;
            if(*(volatile int16_t *)(*(volatile int *)(param_1+0xa8)+0x24)==0) goto L90;
            piVar3=rpmsg_virtio_shm_pool_get_buffer(*(volatile uint32_t *)(param_1+0xb0),*(volatile uint32_t *)(param_1+0x94));
            *param_2=*(volatile int *)(param_1+0x94);
            uStack_24=uStack_24&0xffff;
            process_sync_buffer(addr58);
            if(piVar3!=0) goto L70;
        } else {
L90:
            process_sync_buffer(addr58);
        }
        if(param_3==0) return 0;
        k_sleep(0x21,0);
        param_3=param_3-1;
    }
    {
        int p3_0=*(volatile int *)piVar3;
        int p3_1=*(volatile int *)((int)piVar3+4);
        *(volatile int *)(p3_0+4)=p3_1;
        *(volatile int *)(p3_1)=p3_0;
        *(volatile int *)((int)piVar3)=(int)piVar3;
        *(volatile int *)((int)piVar3+4)=(int)piVar3;
        if(iVar4==0){ *param_2=*(volatile int *)(param_1+0x94); }
    }
L6a:
    process_sync_buffer(addr58);
L70:
    *(volatile int *)((int)piVar3+8)=(int)(uStack_24>>0x10);
    *param_2=*(volatile int *)param_2-0x10;
    return (int*)((int)piVar3+0x10);
}

/* ---- cbor_decode_is_exhausted.c ---- */
/* readable reconstruction; identity: FUN_00085d5c @ 0x00085d5c
 * public-name: cbor_decode_is_exhausted
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   cbor_decode_is_exhausted                 <= FUN_00085d5c @ 0x00085d5c
 */
/* Reconstructed FUN_00085d5c @ 0x85d5c  (parity: 300/300 trials, PROVEN) */

int cbor_decode_is_exhausted(unsigned int param_1) {
    if (param_1 != 0 && *(char *)(param_1 + 0x10) != 0) {
        return *(int *)(param_1 + 0xc) == 0;
    }
    return 1;
}

/* ================================================================ */
/* member unit: cbor_decode_precheck.c */
/* ================================================================ */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_00085d82 @ 0x00085d82
 * public-name: cbor_decode_precheck
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   cbor_decode_is_exhausted                 <= FUN_00085d5c @ 0x00085d5c
 *   zcbor_backup_store_count                 <= FUN_00085d70 @ 0x00085d70
 *   cbor_decode_precheck                     <= FUN_00085d82 @ 0x00085d82
 */
/* Reconstructed FUN_00085d82 @ 0x85d82  (parity: 300/300 trials, PROVEN) */

extern int cbor_decode_is_exhausted(unsigned int);
extern void zcbor_backup_store_count(unsigned int*,unsigned int);
int cbor_decode_precheck(unsigned int *param_1)
{
  int iVar1;
  iVar1 = cbor_decode_is_exhausted(param_1[5]);
  if (iVar1 != 0) {
    if (param_1[0] < param_1[3]) {
      return iVar1;
    }
    zcbor_backup_store_count(param_1,8);
  }
  return 0;
}

