/*
 * Cohesive translation unit for the `lib' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 2 functions below were 2 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   settings_nvs_read_fn.c
 *   atomic_and_0.c
 */
/* ---- settings_nvs_read_fn.c ---- */
#include "g1_app_symbols.h"
#include <stdint.h>
/* readable reconstruction; identity: FUN_0007f210 @ 0x0007f210
 * public-name: settings_nvs_read_fn
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   settings_nvs_read_latest                 <= FUN_0007e9dc @ 0x0007e9dc
 *   settings_nvs_read_fn                     <= FUN_0007f210 @ 0x0007f210
 */
/* Reconstructed FUN_0007f210 @ 0x7f210  (parity: 300/300 trials, PROVEN) */

extern int settings_nvs_read_latest(int a, int b, int c, int d);
int settings_nvs_read_fn(unsigned int *param_1, int param_2, int param_3) {
    unsigned short h = *(unsigned short*)((char*)param_1 + 4);
    int iVar1 = settings_nvs_read_latest((int)param_1[0], (int)h, param_2, param_3);
    if (param_3 <= iVar1) iVar1 = param_3;
    return iVar1;
}

/* ---- atomic_and_0.c ---- */
/* readable reconstruction; identity: FUN_0007f3f0 @ 0x0007f3f0
 * public-name: atomic_and_0
 * durable-map: recon/catalogs/function_names_app.json
 */
/* Reconstructed atomic_and_0 @ 0x0007f3f0 (FUN_0007f3f0; CFG-verified). */
/* Pinned Zephyr 3.4.99 owner: include/zephyr/sys/atomic_builtin.h. */
int32_t atomic_and_0(volatile int32_t *target, int32_t value)
{ return __atomic_fetch_and(target, value, __ATOMIC_SEQ_CST); }

