/*
 * Cohesive translation unit for the `lib' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 4 functions below were 4 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   gatt_remove_peer_from_attr.c
 *   gatt_ccc_write.c
 *   gatt_write_ccc.c
 *   gatt_cf_write.c
 */
/* ---- gatt_remove_peer_from_attr.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_0005a3c4 @ 0x0005a3c4
 * public-name: gatt_remove_peer_from_attr
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ble_conn_unref                           <= FUN_000566a4 @ 0x000566a4
 *   bt_conn_lookup_addr_le                   <= FUN_00056e74 @ 0x00056e74
 *   sc_clear                                 <= FUN_0005a090 @ 0x0005a090
 *   gatt_remove_peer_from_attr               <= FUN_0005a3c4 @ 0x0005a3c4
 *   bt_addr_le_is_bonded                     <= FUN_00080f92 @ 0x00080f92
 *   bt_conn_is_peer_addr_le                  <= FUN_000814e6 @ 0x000814e6
 *   bt_addr_le_copy_828da                    <= FUN_000828da @ 0x000828da
 * address symbols (name @ address):
 *   ADDR_gatt_ccc_write_THUMB                @ 0x0005a465
 *   rodata_f2b3a                             @ 0x000f2b3a
 *   g_bt_gatt_sc_ccc                         @ 0x20002a20
 */
/* Reconstructed FUN_0005a3c4 @ 0x5a3c4  (parity: 300/300 trials, PROVEN) */
#include <stdint.h>
typedef uint32_t u32; typedef uint8_t u8; typedef uint16_t u16;
typedef void (*fp)(int);
extern void ble_conn_unref(void);
extern int bt_conn_lookup_addr_le(int, void*);
extern void sc_clear(int);
extern int bt_addr_le_is_bonded(unsigned char, const void*);
extern int bt_conn_is_peer_addr_le(int,int,void*);
extern void bt_addr_le_copy_828da(void*, const void*);
u32 gatt_remove_peer_from_attr(int param_1, u32 param_2, int param_3){
    if( (*(int*)(param_1+8) == ADDR_gatt_ccc_write_THUMB /*=0x5a465*/)
        && (({u8* puVar2 = *(u8**)(param_1+0xc); *(short*)(puVar2+10) != 0;})) ){
        u8* puVar2 = *(u8**)(param_1+0xc);
        if(*(short*)(puVar2+8) != 0){
            u8* puVar3 = puVar2+1;
            int iVar1 = bt_conn_is_peer_addr_le(param_3, *puVar2, puVar3);
            if(iVar1 == 0){
                iVar1 = bt_conn_lookup_addr_le(*puVar2, puVar3);
                if(iVar1 != 0){
                    if(*(char*)(iVar1+0xd) == 7){ ble_conn_unref(); return 1; }
                    ble_conn_unref();
                }
            } else {
                iVar1 = bt_addr_le_is_bonded(*(u8*)(param_3+8), param_3+0x90);
                if(iVar1 == 0){
                    if(puVar2 == (u8*)((unsigned long)&g_bt_gatt_sc_ccc) /*=0x20002a20*/) sc_clear(param_3);
                    bt_addr_le_copy_828da(puVar3, ((unsigned long)&rodata_f2b3a) /*=0xf2b3a*/);
                    *puVar2 = 0;
                    *(u16*)(puVar2+8) = 0;
                } else {
                    bt_addr_le_copy_828da(puVar3, param_3+0x90);
                }
            }
        }
        *(u16*)(puVar2+10) = 0;
        if(*(fp*)(puVar2+0xc) != 0){
            (*(fp*)(puVar2+0xc))(param_1);
        }
    }
    return 1;
}

/* ---- gatt_ccc_write.c ---- */
/* readable reconstruction; identity: FUN_0005a464 @ 0x0005a464
 * public-name: gatt_ccc_write
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ccc_match_conn_cfg                       <= FUN_00059c48 @ 0x00059c48
 *   gatt_delayed_store_enqueue               <= FUN_00059d24 @ 0x00059d24
 *   gatt_ccc_write                           <= FUN_0005a464 @ 0x0005a464
 *   gatt_ccc_changed                         <= FUN_000825c0 @ 0x000825c0
 *   bt_addr_le_copy_828da                    <= FUN_000828da @ 0x000828da
 *   log_msg_create_3arg                      <= FUN_00082a42 @ 0x00082a42
 * address symbols (name @ address):
 *   rodata_88128                             @ 0x00088128
 *   rodata_f2b3a                             @ 0x000f2b3a
 *   rodata_f486f                             @ 0x000f486f
 */
/* Reconstructed FUN_0005a464 @ 0x5a464  (parity: 300/300 trials, PROVEN) */
extern int ccc_match_conn_cfg(int,int);
extern void gatt_delayed_store_enqueue(int,int,int);
extern void gatt_ccc_changed(int,int);
extern void log_msg_create_3arg(uint32_t,int,void*);

int gatt_ccc_write(int param_1, int param_2, uint16_t *param_3, int param_4, short param_5){
    int iVar5 = *(volatile int *)(param_2+0xc);
    uint32_t local_28, local_24;
    if (param_5 == 0){
        if ((uint32_t)(param_4 - 1) < 2){
            uint16_t uVar4 = (uint16_t)(uint8_t)*(volatile uint8_t *)param_3;
            if (param_4 != 1) uVar4 = *(volatile uint16_t *)param_3;
            volatile uint8_t *puVar2 = (volatile uint8_t*)ccc_match_conn_cfg(param_1, iVar5);
            if (puVar2 == 0){
                if (uVar4 == 0) return param_4;
                puVar2 = (volatile uint8_t*)ccc_match_conn_cfg(0, iVar5);
                if (puVar2 == 0){
                    local_24 = ((unsigned long)&rodata_f486f) /*=0xf486f*/; local_28 = 2;
                    log_msg_create_3arg(((unsigned long)&rodata_88128) /*=0x88128*/, 0x1080, &local_28);
                    return -0x11;
                }
                bt_addr_le_copy_828da((void*)(puVar2+1), param_1+0x90);
                *puVar2 = *(volatile uint8_t *)(param_1+8);
            }
            {
                volatile uint32_t *cp = (volatile uint32_t*)(iVar5+0x10);
                if (*cp != 0){
                    int iVar3 = ((int(*)(int,int,uint16_t))(*cp))(param_1,param_2,uVar4);
                    if (iVar3 < 0) return iVar3;
                    if ((uint32_t)(iVar3 - 1) > 1) return -0xe;
                }
            }
            uint16_t uVar1 = *(volatile uint16_t *)(puVar2+8);
            *(volatile uint16_t *)(puVar2+8) = uVar4;
            if (*(volatile uint16_t *)(iVar5+10) != uVar4) gatt_ccc_changed(param_2, iVar5);
            if (uVar1 != uVar4) gatt_delayed_store_enqueue(*(volatile uint8_t *)(param_1+8), param_1+0x90, 0);
            if (uVar4 == 0){
                bt_addr_le_copy_828da((void*)(puVar2+1), ((unsigned long)&rodata_f2b3a) /*=0xf2b3a*/);
                *puVar2 = 0;
                *(volatile uint16_t *)(puVar2+8) = 0;
            }
        } else param_4 = -0xd;
    } else param_4 = -7;
    return param_4;
}

/* ---- gatt_write_ccc.c ---- */
/* readable reconstruction; identity: FUN_0005a540 @ 0x0005a540
 * public-name: gatt_write_ccc
 * durable-map: recon/catalogs/function_names_app.json
 * address symbols (name @ address):
 *   ADDR_gatt_write_ccc_rsp_THUMB            @ 0x0005a1b1
 *   ADDR_gatt_write_ccc_buf_THUMB            @ 0x00082b6f
 */
/* gatt_write_ccc @ 0x0005a540; raw FUN_0005a540 */

extern int atomic_or_0(volatile long*, long); /* FUN_000826e0 */
extern int gatt_req_send(void *, void *, void *, void *, uint32_t, uint32_t); /* FUN_00082aee */

int gatt_write_ccc(void *connection, uint8_t *params)
{
    atomic_or_0((uint32_t *)(params + 0x14), 8);
    return gatt_req_send(connection, (void *)ADDR_gatt_write_ccc_rsp_THUMB /*=0x5a1b1*/, params,
                         (void *)ADDR_gatt_write_ccc_buf_THUMB /*=0x82b6f*/, 0x12, 4);
}

/* ---- gatt_cf_write.c ---- */
/* readable reconstruction; identity: FUN_0005a5bc @ 0x0005a5bc
 * public-name: gatt_cf_write
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   find_cf_cfg                              <= FUN_00059c04 @ 0x00059c04
 *   gatt_cf_write                            <= FUN_0005a5bc @ 0x0005a5bc
 *   bt_addr_le_copy_828da                    <= FUN_000828da @ 0x000828da
 *   log_msg_create_3arg                      <= FUN_00082a42 @ 0x00082a42
 *   set_change_aware                         <= FUN_00082bb8 @ 0x00082bb8
 * address symbols (name @ address):
 *   rodata_88128                             @ 0x00088128
 *   rodata_f4889                             @ 0x000f4889
 */
/* Reconstructed FUN_0005a5bc @ 0x5a5bc  (parity: 300/300 trials, PROVEN) */

extern uint8_t* find_cf_cfg(void);
extern void set_change_aware(void*, int);

int gatt_cf_write(int param_1, uint32_t param_2, uint8_t *param_3, int param_4, uint16_t param_5){
  uint8_t *puVar1;
  uint32_t uVar2;
  volatile uint32_t local_20, local_1c;
  if (param_5 < 2){
    if ((int)((uint32_t)param_5 + param_4) < 2){
      puVar1 = find_cf_cfg();
      if (puVar1 == 0 && (puVar1 = find_cf_cfg(), puVar1 == 0)){
        param_4 = -0x11;
        local_1c = ((unsigned long)&rodata_f4889) /*=0xf4889*/;
        local_20 = 2;
        log_msg_create_3arg(((unsigned long)&rodata_88128) /*=0x88128*/, 0x1080, (void*)&local_20);
      } else {
        if (param_4 != 0){
          uVar2 = 0;
          do {
            if ((((puVar1[8] >> (uVar2 & 0xff)) & 1) != 0) &&
                (((*param_3 >> (uVar2 & 0xff)) & 1) == 0)){
              return -0x13;
            }
            uVar2 = uVar2 + 1;
          } while (uVar2 != 3);
          puVar1[8] = puVar1[8] | (*param_3 & 7);
        }
        bt_addr_le_copy_828da((void*)(puVar1+1), param_1 + 0x90);
        *puVar1 = *(uint8_t*)(param_1 + 8);
        set_change_aware((void*)puVar1, 1);
      }
    } else {
      param_4 = -0xd;
    }
  } else {
    param_4 = -7;
  }
  return param_4;
}

