/*
 * Cohesive translation unit for the `notify' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 6 functions below were 6 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   notify_config_change_if_connected.c
 *   ancs_notify_sync_init.c
 *   ancs_get_conn_ctx.c
 *   ancs_ctx_init.c
 *   ancs_discover_start.c
 *   ancs_conn_event_signal_and_mode.c
 */

/* File-scope forward declarations for every struct/union tag this
 * unit names.  Without them a tag whose only appearance in a member
 * is inside a parameter list has PARAMETER-LIST scope, so two
 * textually IDENTICAL declarations in two members declare two
 * different incomplete types and the second is a conflicting
 * redeclaration (C11 6.2.1p7).  Incomplete-type forward
 * declarations emit no code. */
struct k_mutex;
struct k_sem;
/* ---- notify_config_change_if_connected.c ---- */
#include "g1_app_symbols.h"
struct k_mutex;
#include "../../../headers/g1_log.h"
/* readable reconstruction; identity: FUN_00017e84 @ 0x00017e84
 * public-name: notify_config_change_if_connected
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   notify_config_change_if_connected        <= FUN_00017e84 @ 0x00017e84
 *   get_ancs_conn_handle                     <= FUN_00019b2c @ 0x00019b2c
 *   is_battery_critical                      <= FUN_00032ee4 @ 0x00032ee4
 *   gatt_notify_config_change                <= FUN_0004f518 @ 0x0004f518
 *   k_mutex_lock                             <= FUN_000723b8 @ 0x000723b8
 *   k_mutex_unlock                           <= FUN_00072558 @ 0x00072558
 * address symbols (name @ address):
 *   rodata_9a155                             @ 0x0009a155   [INLINED -- G6 literal batch]
 *   g_settings_notify_mutex                  @ 0x20006a1c
 */
/* Reconstructed FUN_00017e84 @ 0x17e84  (parity: 300/300 trials, PROVEN) */
extern unsigned int get_ancs_conn_handle(void);
extern long long is_battery_critical(void);
extern int get_device_info(void);
extern void k_mutex_lock(unsigned,unsigned,unsigned,unsigned);
extern int gatt_notify_config_change(int,unsigned,unsigned);
extern int k_mutex_unlock(struct k_mutex *);
unsigned notify_config_change_if_connected(unsigned param_1, unsigned param_2){
    int r6 = get_ancs_conn_handle();
    long long uVar3 = is_battery_critical();
    int r4;
    if ((int)uVar3 != 0) goto L_work;
    if (r6 == 0) goto L_dc;
    {
        int t = get_device_info();
        if (*(char*)(t + 0xae3) != 0) goto L_dc;
        t = get_device_info();
        if (*(int*)(t + 0x9b4) == 0) goto L_dc;
    }
L_work:
    k_mutex_lock(((unsigned long)&g_settings_notify_mutex) /*=0x20006a1c*/, (unsigned)((unsigned long long)uVar3 >> 32), 0xffffffff, 0xffffffff);
    r4 = gatt_notify_config_change(0, param_1, param_2);
    k_mutex_unlock(((unsigned long)&g_settings_notify_mutex) /*=0x20006a1c*/);
    if (r4 == 0) return 0;
    log_message(((unsigned long)"Failed to send data over BLE connection: ret %d len %d \n") /*=0x9a155*/, r4, param_2);
    goto L_dc;
L_dc:
    r4 = -1;
    return (unsigned)r4;
}

/* ---- ancs_notify_sync_init.c ---- */
/* readable reconstruction; identity: FUN_000181f0 @ 0x000181f0
 * public-name: ancs_notify_sync_init
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ancs_notify_sync_init                    <= FUN_000181f0 @ 0x000181f0
 *   ancs_gatt_client_cb_set                  <= FUN_0004f500 @ 0x0004f500
 * address symbols (name @ address):
 *   g_ancs_notify_sync_obj                   @ 0x20002310
 */
/* Reconstructed FUN_000181f0 @ 0x181f0  (parity: 300/300 trials, PROVEN) */

extern int ancs_gatt_client_cb_set(const unsigned long*);
int ancs_notify_sync_init(void) {
    return ancs_gatt_client_cb_set((void*)((unsigned long)&g_ancs_notify_sync_obj) /*=0x20002310*/);
}

/* ---- ancs_get_conn_ctx.c ---- */
/* readable reconstruction; identity: FUN_000181fc @ 0x000181fc
 * public-name: ancs_get_conn_ctx
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ancs_get_conn_ctx                        <= FUN_000181fc @ 0x000181fc
 * address symbols (name @ address):
 *   g_ble_conn_ctx_ptr                       @ 0x20006a30
 */
/* Reconstructed FUN_000181fc @ 0x181fc  (parity: 300/300 trials, PROVEN) */

int ancs_get_conn_ctx(void) {
    return *(volatile unsigned int *)((unsigned long)&g_ble_conn_ctx_ptr) /*=0x20006a30*/;
}

/* ---- ancs_ctx_init.c ---- */
/* readable reconstruction; identity: FUN_00018208 @ 0x00018208
 * public-name: ancs_ctx_init
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ancs_ctx_init                            <= FUN_00018208 @ 0x00018208
 *   malloc                                   <= FUN_00076d6c @ 0x00076d6c
 *   kmutex_dlist_init                        <= FUN_000864c2 @ 0x000864c2
 *   z_impl_k_sem_init                        <= FUN_00086534 @ 0x00086534
 *   memset_bytes                             <= FUN_00086c78 @ 0x00086c78
 * address symbols (name @ address):
 *   ADDR_notify_config_change_if_connected_THUMB @ 0x00017e85
 *   ADDR_init_ble_work_thread_THUMB          @ 0x0002201d
 *   g_settings_notify_mutex                  @ 0x20006a1c
 *   g_ble_conn_ctx_ptr                       @ 0x20006a30
 */
/* Reconstructed FUN_00018208 @ 0x18208  (parity: 300/300 trials, PROVEN) */

#include <stdint.h>
extern void kmutex_dlist_init(unsigned);
extern void z_impl_k_sem_init(void*,int,int);
extern void *malloc(size_t);
extern void memset_bytes(unsigned,int,int,unsigned);
void ancs_ctx_init(uint32_t *param_1,unsigned param_2,unsigned param_3,unsigned param_4){
  uint32_t *puVar1; unsigned uVar2;
  param_1[0x93]=(uint32_t)(param_1+0xe5);
  *param_1=ADDR_init_ble_work_thread_THUMB /*=0x2201d*/;
  kmutex_dlist_init(((unsigned long)&g_settings_notify_mutex) /*=0x20006a1c*/);
  param_1[3]=ADDR_notify_config_change_if_connected_THUMB /*=0x17e85*/;
  z_impl_k_sem_init(param_1+0x86,0,1);
  z_impl_k_sem_init(param_1+0x8c,0,2);
  param_1[0x94]=(uint32_t)(param_1+0x230);
  puVar1=(uint32_t*)((unsigned long)&g_ble_conn_ctx_ptr) /*=0x20006a30*/;
  *(volatile uint8_t *)((int)param_1+0x365)=0;
  *(volatile uint8_t *)((int)param_1+0x366)=0;
  *(volatile uint8_t *)((int)(param_1+0xd9))=0;
  *(volatile uint32_t *)puVar1=(uint32_t)param_1;
  uVar2=malloc(0x15);
  param_1[0x95]=uVar2;
  memset_bytes(uVar2,0,0x15,param_4);
  return;
}

/* ---- ancs_discover_start.c ---- */
/* readable reconstruction; identity: FUN_000182c8 @ 0x000182c8
 * public-name: ancs_discover_start
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ancs_discover_start                      <= FUN_000182c8 @ 0x000182c8
 *   gatt_dm_start                            <= FUN_0004ed8c @ 0x0004ed8c
 * address symbols (name @ address):
 *   rodata_88a00                             @ 0x00088a00
 *   rodata_9a401                             @ 0x0009a401   [INLINED -- G6 literal batch]
 *   g_ancs_discover_params                   @ 0x20006abc
 */
/* Reconstructed FUN_000182c8 @ 0x182c8  (parity: 300/300 trials, PROVEN) */

extern int gatt_dm_start(unsigned int a, void *b, unsigned int c, unsigned int d, unsigned int e);

void ancs_discover_start(unsigned int param_1, unsigned short param_2, unsigned int param_3)
{
    int iVar1;
    unsigned int request;
    (void)param_3;
    request = 0x18010000U | (param_2 & 0xff00U);
    iVar1 = gatt_dm_start(param_1, &request, ((unsigned long)&rodata_88a00) /*=0x88a00*/, ((unsigned long)&g_ancs_discover_params) /*=0x20006abc*/, param_1);
    if (iVar1 != 0) {
        log_message(((unsigned long)"Failed to start discovery for GATT Service (err %d)\n") /*=0x9a401*/, iVar1);
    }
}

/* ---- ancs_conn_event_signal_and_mode.c ---- */
struct k_sem;
/* readable reconstruction; identity: FUN_00018300 @ 0x00018300
 * public-name: ancs_conn_event_signal_and_mode
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   ancs_conn_event_signal_and_mode          <= FUN_00018300 @ 0x00018300
 *   k_sem_give                               <= FUN_00072880 @ 0x00072880
 * address symbols (name @ address):
 *   rodata_9a436                             @ 0x0009a436   [INLINED -- G6 literal batch]
 *   g_ancs_active_conn                       @ 0x20006ab8
 */
/* Reconstructed FUN_00018300 @ 0x18300  (parity: 300/300 trials, PROVEN) */

extern void k_sem_give(struct k_sem *);
extern unsigned int change_work_mode_to(unsigned int);
void ancs_conn_event_signal_and_mode(int param_1, unsigned int param_2)
{
    log_message(((unsigned long)"Updated MTU: TX: %d RX: %d bytes\n") /*=0x9a436*/);
    if (99 < param_2) {
        k_sem_give(*(volatile int *)((unsigned long)&g_ancs_active_conn) /*=0x20006ab8*/ + 0x230);
        if (param_2 == 0x1f2) {
            change_work_mode_to(1);
            return;
        }
    }
}

