/*
 * Cohesive translation unit for the `notify' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 2 functions below were 2 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   send_data_in_ble_chunks.c
 *   post_notification_cmd_process.c
 */
/* ---- send_data_in_ble_chunks.c ---- */
#include "g1_app_symbols.h"
#include <stddef.h>
/* readable reconstruction; identity: FUN_0003384c @ 0x0003384c
 * public-name: send_data_in_ble_chunks
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   strlen                                   <= FUN_0000ef12 @ 0x0000ef12
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   send_notification_app_whitelist          <= FUN_00033730 @ 0x00033730
 *   send_data_in_ble_chunks                  <= FUN_0003384c @ 0x0003384c
 *   strncmp                                  <= FUN_00087036 @ 0x00087036
 * address symbols (name @ address):
 *   rodata_883c8                             @ 0x000883c8
 *   rodata_a7bf5                             @ 0x000a7bf5   [INLINED -- G6 literal batch]
 *   rodata_a833e                             @ 0x000a833e   [INLINED -- G6 literal batch]
 *   g_log_use_alt_sink                       @ 0x20007554
 */
/* Full owned-CFG reconstruction FUN_0003384c @ 0x3384c. */
#include <stdint.h>
#include "../../../headers/g1_log.h"
#include "../../../headers/g1_dedupe.h"

extern size_t strlen(const char *);
extern int get_device_info(void);
extern unsigned long send_notification_app_whitelist(unsigned char*, const char*, const char*, unsigned long);
extern int strncmp(const char *, const char *, size_t);

/* G7-B2 defect fix.  The body was `uint32_t` and `return`ed the result of the
 * logging call.  Both sinks are `void` (recon/headers/g1_log.h), and the
 * shipped function never computes a return value: 0x338d4 (the NULL-request
 * path) pops straight to pc with the incoming NULL still in r0, and all three
 * other exits are TAIL calls -- `b.w 0x19c70`, `b.w 0x7dda4` and
 * `b.w 0x33730` -- so r0 is always the callee's scratch.  Both call sites,
 * ancs_notification_forward.c and post_notification_cmd_response.c, already
 * declared it `extern void send_data_in_ble_chunks(void *)`; this definition
 * was the odd one out.  As `void` every exit stays a tail call and the
 * emitted sequence is unchanged. */
void send_data_in_ble_chunks(const uint8_t *request)
{
    const uint32_t *commands = (const uint32_t *)((unsigned long)&rodata_883c8) /*=0x883c8*/;
    uint32_t command_copy[9];
    unsigned int i;

    if (request == 0)
        return;

    for (i = 0; i < 9; ++i)
        command_copy[i] = commands[i];

    for (i = 0; i < 9; ++i) {
        uint32_t value = strlen(command_copy[i]);
        if (strncmp(command_copy[i], request + 0x10, value) == 0) {
            /* 0xa7bf5 has three specifiers, so four arguments; 0x3388c and
             * 0x338a0 load exactly r0..r3.  Only the `return` was wrong. */
            if (*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0) {
                log_message(((unsigned long)"[%s-%d] special package nane:%s,need not send to app !\n") /*=0xa7bf5*/, ((unsigned long)"send_whilelist_app_info_wrapper") /*=0xa833e*/,
                            0x137, request + 0x10);
                return;
            }
            debug_print(((unsigned long)"[%s-%d] special package nane:%s,need not send to app !\n") /*=0xa7bf5*/, ((unsigned long)"send_whilelist_app_info_wrapper") /*=0xa833e*/,
                        0x137, request + 0x10);
            return;
        }
    }

    send_notification_app_whitelist((void *)(get_device_info() + 0x77c),
                         request + 0x10, request + 0x30, 0);
}

/* ---- post_notification_cmd_process.c ---- */
/* readable reconstruction; identity: FUN_000338ec @ 0x000338ec
 * public-name: post_notification_cmd_process
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   audio_fw_load_get_wrapper                <= FUN_00019b54 @ 0x00019b54
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   parse_receiver_msg_pack_pkcs7            <= FUN_00019da4 @ 0x00019da4
 *   post_notification_cmd_process            <= FUN_000338ec @ 0x000338ec
 *   parse_ncs_notification                   <= FUN_00034980 @ 0x00034980
 *   malloc                                   <= FUN_00076d6c @ 0x00076d6c
 *   free                                     <= FUN_00076d7c @ 0x00076d7c
 *   log_message                              <= FUN_0007dda4 @ 0x0007dda4
 *   memcpy                                   <= FUN_00086c04 @ 0x00086c04
 *   memset_bytes                             <= FUN_00086c78 @ 0x00086c78
 * address symbols (name @ address):
 *   rodata_a7c2d                             @ 0x000a7c2d   [INLINED -- refactor stage 01]
 *   rodata_a7c4a                             @ 0x000a7c4a
 *   rodata_a7c9c                             @ 0x000a7c9c   [INLINED -- refactor stage 01]
 *   rodata_a7cb6                             @ 0x000a7cb6   [INLINED -- refactor stage 01]
 *   rodata_a82c4                             @ 0x000a82c4   [INLINED -- refactor stage 01]
 *   rodata_a82e2                             @ 0x000a82e2   [INLINED -- refactor stage 01]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 *   g_ancs_notify_rx_buf                     @ 0x20007da8
 */
/* Reconstructed FUN_000338ec @ 0x338ec  (parity: 300/300 trials, PROVEN) */
extern unsigned long audio_fw_load_get_wrapper(int, unsigned char*, unsigned long);
extern unsigned int parse_receiver_msg_pack_pkcs7(int, unsigned char*, unsigned int);
extern void parse_ncs_notification(int, int*);
extern void *malloc(size_t);
extern void free(void *);
extern void memcpy(int, int, int);
extern void memset_bytes(void*, int, int);

void post_notification_cmd_process(int param_1, unsigned char *param_2, int param_3)
{
    int *piVar1; unsigned uVar2; int iVar3; unsigned char *puVar4; unsigned uVar5;
    unsigned local_b4; unsigned char auStack_b0[16]; unsigned char auStack_a0[132];

    if(param_1==0 || param_2==0 || param_3==0){
        if(1 < *(volatile int *)((unsigned long)&g_log_level) /*=0x2000230c*/){
            if(*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ != 0){ debug_print(((unsigned long)"%s(): input param invalid !\n") /*=0xa7c2d*/, ((unsigned long)"post_notification_cmd_process") /*=0xa82e2*/); return; }
            log_message(((unsigned long)"%s(): input param invalid !\n") /*=0xa7c2d*/, ((unsigned long)"post_notification_cmd_process") /*=0xa82e2*/); return;
        }
    } else {
        puVar4 = *(unsigned char**)(param_1+0x10);
        local_b4 = 0;
        memset_bytes((int)auStack_b0, 0, 0x10);
        *(unsigned char*)&local_b4 = *param_2;
        *puVar4 = *param_2;
        puVar4[1] = param_2[1];
        *(unsigned*)(param_1+0x14) = *(unsigned short*)(puVar4+2) + 4;
        piVar1 = (int*)((unsigned long)&g_ancs_notify_rx_buf) /*=0x20007da8*/;
        uVar5 = (unsigned)(unsigned char)puVar4[1];
        if(uVar5==2 || uVar5==4){
            *(unsigned short*)(puVar4+2) = 0x1b4;
            memcpy((int)(puVar4+4), param_3, 0x1b4);
            if(2 < *(volatile int *)((unsigned long)&g_log_level) /*=0x2000230c*/){
                G1_LOG_ROUTE(*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0, ((unsigned long)&rodata_a7c4a) /*=0xa7c4a*/, ((unsigned long)"post_notification_cmd_process") /*=0xa82e2*/, uVar5);
            }
            audio_fw_load_get_wrapper(param_1, (int)auStack_a0, 8);
        } else {
            if(*(volatile int *)((unsigned long)&g_ancs_notify_rx_buf) /*=0x20007da8*/ == 0){
                iVar3 = malloc(0x800);
                *piVar1 = iVar3;
                if(iVar3==0){
                    G1_LOG_ROUTE(*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0, ((unsigned long)"[%s-%d] malloc failed !!\n") /*=0xa7c9c*/, ((unsigned long)"post_notification_cmd_process") /*=0xa82c4*/, 0x19f);
                } else {
                    memset_bytes(iVar3, 0, 0x800);
                }
            }
            if(*piVar1 != 0){
                iVar3 = parse_receiver_msg_pack_pkcs7(*piVar1, param_3, puVar4[2]);
                uVar2 = local_b4;
                *((unsigned char*)&local_b4 + 1) = (unsigned char)iVar3;
                *((unsigned char*)&local_b4 + 3) = (unsigned char)(uVar2 >> 24);
                *((unsigned char*)&local_b4 + 2) = *(unsigned char*)(param_3+1);
                if(iVar3 == 0xc9){
                    parse_ncs_notification(*piVar1, (int)(puVar4+4));
                    if(2 < *(volatile int *)((unsigned long)&g_log_level) /*=0x2000230c*/){
                        G1_LOG_ROUTE(*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0, ((unsigned long)"%s(): ncs data receive okay !\n\n") /*=0xa7cb6*/, ((unsigned long)"post_notification_cmd_process") /*=0xa82e2*/);
                    }
                    *(unsigned short*)(puVar4+2) = 0x1b4;
                    audio_fw_load_get_wrapper(param_1, (int)auStack_a0, 8);
                    *((unsigned char*)&local_b4 + 1) = 0xc9;
                    free(*piVar1);
                    *piVar1 = 0;
                }
            }
            (*(void(**)(int,...))(param_1+0xc))((int)&local_b4, 0x14);
        }
    }
    return;
}

