/*
 * Cohesive translation unit for the `notify' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 2 functions below were 2 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   parse_whitelist_json.c
 *   whitelist_contains_app.c
 */
/* ---- parse_whitelist_json.c ---- */
#include "g1_app_symbols.h"
/* readable reconstruction; identity: FUN_00034dbc @ 0x00034dbc
 * public-name: parse_whitelist_json
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   parse_whitelist_json                     <= FUN_00034dbc @ 0x00034dbc
 *   cjson_delete                             <= FUN_00064b1c @ 0x00064b1c
 *   cbor_decode_start_default                <= FUN_0008500c @ 0x0008500c
 *   sllist_count_nodes                       <= FUN_00085020 @ 0x00085020
 *   sllist_node_at_index                     <= FUN_00085030 @ 0x00085030
 *   sllist_find_by_name_ci                   <= FUN_0008503c @ 0x0008503c
 *   cjson_is_array                           <= FUN_000850c8 @ 0x000850c8
 *   memset_bytes                             <= FUN_00086c78 @ 0x00086c78
 *   strncpy_zero_pad                         <= FUN_0008705a @ 0x0008705a
 * address symbols (name @ address):
 *   rodata_9a1dd                             @ 0x0009a1dd
 *   rodata_9e1b6                             @ 0x0009e1b6
 *   rodata_9e235                             @ 0x0009e235
 *   rodata_a8604                             @ 0x000a8604   [INLINED -- G6 literal batch]
 *   rodata_a862c                             @ 0x000a862c
 *   rodata_a8638                             @ 0x000a8638
 *   rodata_a864e                             @ 0x000a864e
 *   rodata_a866e                             @ 0x000a866e
 *   rodata_a869b                             @ 0x000a869b
 *   rodata_a870b                             @ 0x000a870b
 *   rodata_f33e4                             @ 0x000f33e4
 *   rodata_f3630                             @ 0x000f3630
 *   g_log_use_alt_sink                       @ 0x20007554
 *   g_app_whitelist_buffer                   @ 0x2001a22c
 */
/* Reconstructed FUN_00034dbc @ 0x34dbc. */
#include <stdint.h>
#include "../../../headers/g1_log.h"
#include "g1_notify.h"

extern int sllist_node_at_index(int object);
extern void memset_bytes(void*, int, int);
extern void strncpy_zero_pad(void *destination, const void *source,
                         unsigned int limit);

#define REPORT_ERROR(format_) do {                                      \
    if (*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0)                              \
        log_message((format_));                                         \
    else                                                                \
        debug_print((format_));                                        \
} while (0)

uint32_t parse_whitelist_json(uint32_t request, uint32_t unused_2,
                      uint32_t unused_3)
{
    volatile uint8_t *const output = (volatile uint8_t *)((unsigned long)g_app_whitelist_buffer) /*=0x2001a22c*/;
    int root = cbor_decode_start_default();
    int object;
    uint32_t error_format;
    uint8_t item_count;
    uint8_t source_index;
    uint8_t output_index;
    (void)unused_2;
    (void)unused_3;

    if (root == 0) {
        if (*(volatile int *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0)
            log_message(((unsigned long)"error root JSON NODE,json_buffer is %s\n") /*=0xa8604*/, request);
        else
            debug_print(((unsigned long)"error root JSON NODE,json_buffer is %s\n") /*=0xa8604*/, request);
        return 0;
    }

    memset_bytes((void *)output, 0, 0x15e2);
    object = sllist_find_by_name_ci(root, ((unsigned long)&rodata_a862c) /*=0xa862c*/);
    if (object == 0) { error_format = ((unsigned long)&rodata_a8638) /*=0xa8638*/; goto fail; }
    output[0] = (output[0] & 0xfeu) | (*(int *)(object + 0xc) == 2);

    object = sllist_find_by_name_ci(root, ((unsigned long)&rodata_a864e) /*=0xa864e*/);
    if (object == 0) { error_format = 0x000a8659; goto fail; }
    output[0] = (output[0] & 0xfdu) |
                ((uint32_t)(*(int *)(object + 0xc) == 2) << 1);

    object = sllist_find_by_name_ci(root, ((unsigned long)&rodata_a866e) /*=0xa866e*/);
    if (object == 0) { error_format = 0x000a867e; goto fail; }
    output[0] = (output[0] & 0xf7u) |
                ((uint32_t)(*(int *)(object + 0xc) == 2) << 3);

    object = sllist_find_by_name_ci(root, ((unsigned long)&rodata_a869b) /*=0xa869b*/);
    if (object == 0) { error_format = 0x000a86ab; goto fail; }
    output[0] = (output[0] & 0xfbu) |
                ((uint32_t)(*(int *)(object + 0xc) == 2) << 2);

    object = sllist_find_by_name_ci(root, ((unsigned long)&rodata_9e1b6) /*=0x9e1b6*/);
    if (object == 0) { error_format = 0x000a86c8; goto fail; }
    {
        int nested = sllist_find_by_name_ci(object, ((unsigned long)&rodata_9e235) /*=0x9e235*/);
        if (nested == 0) { error_format = 0x000a86db; goto fail; }
        output[0] = (output[0] & 0xefu) |
                    ((uint32_t)(*(int *)(nested + 0xc) == 2) << 4);
    }

    object = sllist_find_by_name_ci(object, ((unsigned long)&rodata_f3630) /*=0xf3630*/);
    if (object == 0) { error_format = 0x000a86f4; goto fail; }

    if (cjson_is_array() != 0) {
        item_count = (uint8_t)sllist_count_nodes(object);
        if (item_count > 99)
            item_count = 100;
        output[1] = item_count;
        output_index = 0;

        for (source_index = 0; source_index < output[1]; ++source_index) {
            int item = sllist_node_at_index(object);
            int name;
            int value;
            volatile uint8_t *record;

            if (item == 0) {
                REPORT_ERROR(((unsigned long)&rodata_a870b) /*=0xa870b*/);
                continue;
            }
            name = sllist_find_by_name_ci(item, ((unsigned long)&rodata_9a1dd) /*=0x9a1dd*/);
            if (name == 0) {
                REPORT_ERROR(0x000a8724);
                continue;
            }
            value = sllist_find_by_name_ci(item, ((unsigned long)&rodata_f33e4) /*=0xf33e4*/);
            if (value == 0) {
                REPORT_ERROR(0x000a8739);
                continue;
            }

            record = output + (uint32_t)output_index * 0x38 + 2;
            memset_bytes((void *)record, 0, 0x28);
            memset_bytes((void *)(record + 0x28), 0, 0x10);
            strncpy_zero_pad((void *)record, *(const void **)(name + 0x10), 0x27);
            strncpy_zero_pad((void *)(record + 0x28),
                         *(const void **)(value + 0x10), 0x0f);
            output_index = (uint8_t)(output_index + 1);
        }
    }

    cjson_delete(root);
    return 1;

fail:
    REPORT_ERROR(error_format);
    cjson_delete(root);
    return 0;
}

/* ---- whitelist_contains_app.c ---- */
/* readable reconstruction; identity: FUN_00034ff0 @ 0x00034ff0
 * public-name: whitelist_contains_app
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   whitelist_contains_app                   <= FUN_00034ff0 @ 0x00034ff0
 *   log_message                              <= FUN_0007dda4 @ 0x0007dda4
 *   strncmp                                  <= FUN_00087036 @ 0x00087036
 * address symbols (name @ address):
 *   rodata_a8750                             @ 0x000a8750   [INLINED -- G6 literal batch]
 *   g_log_use_alt_sink                       @ 0x20007554
 *   g_app_whitelist_buffer                   @ 0x2001a22c
 *   g_on_whitelist_by_identifier             @ 0x2001a22d
 */
/* Reconstructed FUN_00034ff0 @ 0x34ff0 (strict CFG parity). */
#include "../../../headers/g1_dedupe.h"

extern int strncmp(const void*, unsigned long, unsigned int);

uint32_t whitelist_contains_app(const void *name, const void *identifier)
{
    uint8_t *row;
    uint8_t *end;

    if (name == 0 || identifier == 0) {
        G1_LOG_ROUTE(*(volatile uint32_t *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0, ((unsigned long)"invalid param ! \n") /*=0xa8750*/);
        return 0;
    }

    row = (uint8_t *)((unsigned long)g_app_whitelist_buffer) /*=0x2001a22c*/;
    end = row + (uint32_t)*(volatile uint8_t *)((unsigned long)&g_on_whitelist_by_identifier) /*=0x2001a22d*/ * 0x38U;
    while (row != end) {
        if (strncmp(row + 2, name, 0x28U) == 0 &&
            strncmp(row + 0x2a, identifier, 0x10U) == 0) {
            return 1;
        }
        row += 0x38;
    }
    return 0;
}

