/*
 * Cohesive translation unit for the `gui' module.
 *
 * GENERATED by recon/refactor/transforms/t04_cohesive_tu.py.  Do not
 * edit: a stage tree is regenerated, never hand-patched
 * (recon/refactor/README.md C4).
 *
 * The 5 functions below were 5 separate translation units until this
 * stage.  Each one's text is reproduced VERBATIM and in the order the
 * generated source list gave it, and they were CONSECUTIVE in that list.
 * They were proven able to share a translation unit: no symbol is
 * declared here with two types, no identifier has internal linkage in one
 * member and is named by another, and no local typedef, macro, struct tag
 * or enum constant of one member is visible to a member that names it.
 *
 * members, in link order:
 *   gui_string_draw.c
 *   get_clock_digit_glyph_offset_large.c
 *   get_clock_digit_glyph_offset_small.c
 *   get_font_style3_glyph_offset.c
 *   get_default_font_glyph_offset.c
 */
/* ---- gui_string_draw.c ---- */
#include "g1_app_symbols.h"
#include <stddef.h>
/* readable reconstruction; identity: FUN_000455cc @ 0x000455cc
 * public-name: gui_string_draw
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   strlen                                   <= FUN_0000ef12 @ 0x0000ef12
 *   get_device_info                          <= FUN_000167a8 @ 0x000167a8
 *   debug_print                              <= FUN_00019c70 @ 0x00019c70
 *   atomic_get_3_0                           <= FUN_000431a8 @ 0x000431a8
 *   count_chars_in_default_font_table        <= FUN_00043e58 @ 0x00043e58
 *   resource_manger_get                      <= FUN_0004588c @ 0x0004588c
 *   clean_fb_data                            <= FUN_000471cc @ 0x000471cc
 *   reflash_fb_data_to_lcd                   <= FUN_00047260 @ 0x00047260
 *   fb_blit_rows_copy                        <= FUN_0007d53a @ 0x0007d53a
 * address symbols (name @ address):
 *   rodata_aac62                             @ 0x000aac62   [INLINED -- G6 literal batch]
 *   rodata_aac9f                             @ 0x000aac9f   [INLINED -- G6 literal batch]
 *   g_log_level                              @ 0x2000230c
 *   g_log_use_alt_sink                       @ 0x20007554
 *   g_gui_active_canvas                      @ 0x2000a034
 */
/* Full reconstruction of gui_string_draw @ 0x455cc (280 bytes). */
#include <stdint.h>
#include "../../../headers/g1_log.h"
#include "g1_gui.h"

extern size_t strlen(const char *);
extern int atomic_get_3_0(void);
extern int get_device_info(void);
extern void clean_fb_data(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
extern void reflash_fb_data_to_lcd(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
extern long resource_manger_get(unsigned long, unsigned long, long*, long*, unsigned long*, unsigned long);

int gui_string_draw(uint32_t font, const uint8_t *text, int32_t x, uint32_t y,
                    uint32_t arg5, uint32_t arg6, int32_t *width_out)
{
    int32_t glyph_width = 0, glyph_height = 0;
    uint32_t bitmap = 0;
    int length = strlen(text);
    int32_t cursor = x;

    if (atomic_get_3_0() & 2u)
        clean_fb_data(*(volatile uint32_t *)((unsigned long)&g_gui_active_canvas) /*=0x2000a034*/, 0, x, y, arg5, arg6);

    for (const uint8_t *p = text; p != text + length; ++p) {
        if (*p < 0x20u) {
            if (*(volatile int32_t *)((unsigned long)&g_log_level) /*=0x2000230c*/ > 0) {
                if (*(volatile uint32_t *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0)
                    log_message(0x000aac83u, ((unsigned long)"gui_string_draw") /*=0xaac9f*/);
                else
                    debug_print(0x000aac83u, ((unsigned long)"gui_string_draw") /*=0xaac9f*/);
            }
            continue;
        }

        if (resource_manger_get(font, *p, &glyph_width, &glyph_height, &bitmap, 0) != 0 || bitmap == 0) {
            if (*(volatile int32_t *)((unsigned long)&g_log_level) /*=0x2000230c*/ > 1) {
                if (*(volatile uint32_t *)((unsigned long)&g_log_use_alt_sink) /*=0x20007554*/ == 0)
                    log_message(((unsigned long)"%s(): find ascii postion failed\n") /*=0xaac62*/, ((unsigned long)"gui_string_draw") /*=0xaac9f*/);
                else
                    debug_print(((unsigned long)"%s(): find ascii postion failed\n") /*=0xaac62*/, ((unsigned long)"gui_string_draw") /*=0xaac9f*/);
            }
            continue;
        }

        fb_blit_rows_copy(*(volatile uint32_t *)((unsigned long)&g_gui_active_canvas) /*=0x2000a034*/, bitmap,
                     (glyph_width + (glyph_width < 0)) / 2, glyph_height,
                     cursor, y);
        if ((uint32_t)(*p - 0x20u) <= 0x5eu && font == 3)
            cursor += glyph_width + 3;
        else
            cursor += glyph_width + count_chars_in_default_font_table(*p, p[1]);
    }

    if (atomic_get_3_0() & 2u) {
        uintptr_t state = get_device_info();
        uint32_t left = *(volatile uint32_t *)(state + 0xeb4);
        state = get_device_info();
        reflash_fb_data_to_lcd(left, *(volatile uint32_t *)(state + 0xeb8), x, y, arg5, arg6);
    }
    if (width_out)
        *width_out = cursor - x;
    return 0;
}

/* ---- get_clock_digit_glyph_offset_large.c ---- */
/* readable reconstruction; identity: FUN_00045764 @ 0x00045764
 * public-name: get_clock_digit_glyph_offset_large
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_clock_digit_glyph_offset_large       <= FUN_00045764 @ 0x00045764
 * address symbols (name @ address):
 *   rodata_8ac34                             @ 0x0008ac34
 *   rodata_98fe8                             @ 0x00098fe8
 *   rodata_e5248                             @ 0x000e5248
 */
/* Reconstructed FUN_00045764 @ 0x45764  (parity: 300/300 trials, PROVEN) */

int get_clock_digit_glyph_offset_large(unsigned int param_1, int *param_2, unsigned int *param_3)
{
  int iVar2 = 0;
  unsigned int uVar1 = 0;
  unsigned short *puVar3 = (unsigned short*)((unsigned long)&rodata_98fe8) /*=0x98fe8*/;
  unsigned int key;
  unsigned char val = 0;
  while (1) {
    if (*(volatile int *)((unsigned long)&rodata_8ac34) /*=0x8ac34*/ <= iVar2) {
      return 0;
    }
    key = *(volatile unsigned short *)puVar3;
    val = *(volatile unsigned char *)((char*)puVar3 + 2);
    puVar3 = puVar3 + 2;
    if (key == param_1) break;
    uVar1 = (uVar1 + (unsigned int)val * 0x27) & 0xffff;
    iVar2 = iVar2 + 1;
  }
  *param_2 = (unsigned int)val << 1;
  *param_3 = 0x27;
  return ((unsigned long)&rodata_e5248) /*=0xe5248*/ + uVar1;
}

/* ---- get_clock_digit_glyph_offset_small.c ---- */
/* readable reconstruction; identity: FUN_000457b0 @ 0x000457b0
 * public-name: get_clock_digit_glyph_offset_small
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_clock_digit_glyph_offset_small       <= FUN_000457b0 @ 0x000457b0
 * address symbols (name @ address):
 *   rodata_8ac30                             @ 0x0008ac30
 *   rodata_98fbc                             @ 0x00098fbc
 *   rodata_e4408                             @ 0x000e4408
 */
/* Reconstructed FUN_000457b0 @ 0x457b0  (parity: 300/300 trials, PROVEN) */

int get_clock_digit_glyph_offset_small(unsigned int param_1, int *param_2, unsigned int *param_3)
{
  unsigned int uVar1 = 0;
  int iVar2 = 0;
  volatile unsigned short *puVar3 = (volatile unsigned short *)((unsigned long)&rodata_98fbc) /*=0x98fbc*/;
  int count = *(volatile int *)((unsigned long)&rodata_8ac30) /*=0x8ac30*/;
  unsigned short id;
  unsigned char b;
  while (1) {
    if (count <= iVar2) return 0;
    id = puVar3[0];
    b = (unsigned char)puVar3[1];
    if (id == param_1) break;
    uVar1 = (uVar1 + ((unsigned int)b << 5)) & 0xffff;
    iVar2 += 1;
    puVar3 += 2;
  }
  *param_2 = (unsigned int)b << 1;
  *param_3 = 0x20;
  return ((unsigned long)&rodata_e4408) /*=0xe4408*/ + uVar1;
}

/* ---- get_font_style3_glyph_offset.c ---- */
/* readable reconstruction; identity: FUN_000457f4 @ 0x000457f4
 * public-name: get_font_style3_glyph_offset
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_font_style3_glyph_offset             <= FUN_000457f4 @ 0x000457f4
 * address symbols (name @ address):
 *   rodata_8ac2c                             @ 0x0008ac2c
 *   rodata_98e3c                             @ 0x00098e3c
 *   rodata_e17da                             @ 0x000e17da
 */
/* Reconstructed FUN_000457f4 @ 0x457f4  (parity: 300/300 trials, PROVEN) */

int get_font_style3_glyph_offset(unsigned int param_1, int *param_2, unsigned int *param_3)
{
  unsigned short *puVar6 = (unsigned short*)((unsigned long)&rodata_98e3c) /*=0x98e3c*/;
  int iVar5 = 0;
  int iVar4 = 0;
  unsigned int val = 0;
  unsigned short key;
  int count = *(volatile int *)((unsigned long)&rodata_8ac2c) /*=0x8ac2c*/;
  while (1) {
    if (count <= iVar5) return 0;
    key = *(volatile unsigned short *)puVar6;
    val = *(volatile unsigned char *)((char*)puVar6 + 2);
    puVar6 = puVar6 + 2;
    if ((unsigned int)key == param_1) break;
    iVar4 = (int)(short)(unsigned short)val * 0x1a + iVar4;
    iVar5 = iVar5 + 1;
  }
  *param_2 = val << 1;
  *param_3 = 0x1a;
  return ((unsigned long)&rodata_e17da) /*=0xe17da*/ + iVar4;
}

/* ---- get_default_font_glyph_offset.c ---- */
/* readable reconstruction; identity: FUN_00045840 @ 0x00045840
 * public-name: get_default_font_glyph_offset
 * durable-map: recon/catalogs/function_names_app.json
 * callees (readable <= raw @ address):
 *   get_default_font_glyph_offset            <= FUN_00045840 @ 0x00045840
 * address symbols (name @ address):
 *   g_default_font_glyph_table_count         @ 0x0008ac28
 *   rodata_9890c                             @ 0x0009890c
 *   rodata_e5f62                             @ 0x000e5f62
 */
/* Reconstructed FUN_00045840 @ 0x45840  (parity: 300/300 trials, PROVEN) */

int get_default_font_glyph_offset(unsigned int param_1, int *param_2, unsigned int *param_3)
{
  int iVar2 = 0;
  unsigned int uVar1 = 0;
  unsigned short *puVar3 = (unsigned short*)((unsigned long)&rodata_9890c) /*=0x9890c*/;
  unsigned int key;
  unsigned char val = 0;
  while (1) {
    if (*(volatile int *)((unsigned long)&g_default_font_glyph_table_count) /*=0x8ac28*/ <= iVar2) {
      return 0;
    }
    key = *(volatile unsigned short *)puVar3;
    val = *(volatile unsigned char *)((char*)puVar3 + 2);
    puVar3 = puVar3 + 2;
    if (key == param_1) break;
    uVar1 = (uVar1 + (unsigned int)val * 0x1a) & 0xffff;
    iVar2 = iVar2 + 1;
  }
  *param_2 = (unsigned int)val << 1;
  *param_3 = 0x1a;
  return ((unsigned long)&rodata_e5f62) /*=0xe5f62*/ + uVar1;
}

