/* GENERATED by recon/application/gen_net_ram_relocs.py (P4 iteration 26) -- do not edit.
 *
 * Structural close of the CPUNET absolute-RAM-address collision class.
 * Under G1_COHESIVE_BUILD each macro resolves to real linked storage;
 * otherwise it is the shipped literal, so parity bodies are unchanged.
 */
#ifndef G1_NET_RAM_RELOC_H_
#define G1_NET_RAM_RELOC_H_

#ifdef G1_COHESIVE_BUILD
extern unsigned char g1_net_ram_blk_21000000[];
extern unsigned char g1_net_ram_blk_21000120[];
extern unsigned char g1_net_ram_blk_210001d0[];
extern unsigned char g1_net_ram_blk_21000308[];
extern unsigned char g1_net_ram_blk_21000340[];
extern unsigned char g1_net_ram_blk_21000400[];
extern unsigned char g1_net_ram_blk_210004a8[];
extern unsigned char g1_net_ram_blk_21000570[];
extern unsigned char g1_net_ram_blk_210005e8[];
extern unsigned char g1_net_ram_blk_21000658[];
extern unsigned char g1_net_ram_blk_21000680[];
extern unsigned char g1_net_ram_blk_21000718[];
extern unsigned char g1_net_ram_blk_21000750[];
extern unsigned char g1_net_ram_blk_210008c8[];
extern unsigned char g1_net_ram_blk_210009f8[];
extern unsigned char g1_net_ram_blk_21000a30[];
extern unsigned char g1_net_ram_blk_21000b70[];
extern unsigned char g1_net_ram_blk_21000ba8[];
extern unsigned char g1_net_ram_blk_21000c28[];
extern unsigned char g1_net_ram_blk_21000c68[];
extern unsigned char g1_net_ram_blk_21000c90[];
extern unsigned char g1_net_ram_blk_21000cc0[];
extern unsigned char g1_net_ram_blk_21000cf8[];
extern unsigned char g1_net_ram_blk_21000db0[];
extern unsigned char g1_net_ram_blk_21000ea0[];
extern unsigned char g1_net_ram_blk_21000f90[];
extern unsigned char g1_net_ram_blk_21000fc0[];
extern unsigned char g1_net_ram_blk_21001048[];
extern unsigned char g1_net_ram_blk_21001098[];
extern unsigned char g1_net_ram_blk_210010f0[];
extern unsigned char g1_net_ram_blk_21001118[];
extern unsigned char g1_net_ram_blk_21001208[];
extern unsigned char g1_net_ram_blk_21001448[];
extern unsigned char g1_net_ram_blk_21001498[];
extern unsigned char g1_net_ram_blk_210014d8[];
extern unsigned char g1_net_ram_blk_210015f0[];
extern unsigned char g1_net_ram_blk_21001638[];
extern unsigned char g1_net_ram_blk_21001660[];
extern unsigned char g1_net_ram_blk_210016b0[];
extern unsigned char g1_net_ram_blk_21001740[];
extern unsigned char g1_net_ram_blk_21001bc8[];
extern unsigned char g1_net_ram_blk_21001c88[];
extern unsigned char g1_net_ram_blk_21001ce8[];
extern unsigned char g1_net_ram_blk_21002b60[];
extern unsigned char g1_net_ram_blk_21002b90[];
extern unsigned char g1_net_ram_blk_21004258[];
extern unsigned char g1_net_ram_blk_210042f0[];
extern unsigned char g1_net_ram_blk_210045b0[];
extern unsigned char g1_net_ram_blk_210045e0[];
extern unsigned char g1_net_ram_blk_21004670[];
extern unsigned char g1_net_ram_blk_210047f8[];
extern unsigned char g1_net_ram_blk_21004830[];
extern unsigned char g1_net_ram_blk_21004960[];
extern unsigned char g1_net_ram_blk_21004a30[];
extern unsigned char g1_net_ram_blk_21004a60[];
extern unsigned char g1_net_ram_blk_21004a88[];
extern unsigned char g1_net_ram_blk_21004ae8[];
extern unsigned char g1_net_ram_blk_21004b30[];
extern unsigned char g1_net_ram_blk_21004c98[];
extern unsigned char g1_net_ram_blk_21004da0[];
extern unsigned char g1_net_ram_blk_21004ea0[];
extern unsigned char g1_net_ram_blk_21004fa0[];
extern unsigned char g1_net_ram_blk_210051a8[];
extern unsigned char g1_net_ram_blk_21005250[];
extern unsigned char g1_net_ram_blk_21005a50[];
extern unsigned char g1_net_ram_blk_21006250[];
extern unsigned char g1_net_ram_blk_21006358[];
extern unsigned char g1_net_ram_blk_21006458[];
extern unsigned char g1_net_ram_blk_21007d80[];
extern unsigned char g1_net_ram_blk_21008a00[];

#define G1N_21000000 ((unsigned long)(g1_net_ram_blk_21000000 + 0x0))
#define G1N_21000008 ((unsigned long)(g1_net_ram_blk_21000000 + 0x8))
#define G1N_21000010 ((unsigned long)(g1_net_ram_blk_21000000 + 0x10))
#define G1N_21000018 ((unsigned long)(g1_net_ram_blk_21000000 + 0x18))
#define G1N_2100001c ((unsigned long)(g1_net_ram_blk_21000000 + 0x1c))
#define G1N_21000020 ((unsigned long)(g1_net_ram_blk_21000000 + 0x20))
#define G1N_21000028 ((unsigned long)(g1_net_ram_blk_21000000 + 0x28))
#define G1N_2100003c ((unsigned long)(g1_net_ram_blk_21000000 + 0x3c))
#define G1N_21000040 ((unsigned long)(g1_net_ram_blk_21000000 + 0x40))
#define G1N_21000044 ((unsigned long)(g1_net_ram_blk_21000000 + 0x44))
#define G1N_21000048 ((unsigned long)(g1_net_ram_blk_21000000 + 0x48))
#define G1N_2100004c ((unsigned long)(g1_net_ram_blk_21000000 + 0x4c))
#define G1N_21000050 ((unsigned long)(g1_net_ram_blk_21000000 + 0x50))
#define G1N_21000054 ((unsigned long)(g1_net_ram_blk_21000000 + 0x54))
#define G1N_21000058 ((unsigned long)(g1_net_ram_blk_21000000 + 0x58))
#define G1N_2100005c ((unsigned long)(g1_net_ram_blk_21000000 + 0x5c))
#define G1N_21000078 ((unsigned long)(g1_net_ram_blk_21000000 + 0x78))
#define G1N_21000124 ((unsigned long)(g1_net_ram_blk_21000120 + 0x4))
#define G1N_210001d0 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x0))
#define G1N_210001d4 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x4))
#define G1N_210001dc ((unsigned long)(g1_net_ram_blk_210001d0 + 0xc))
#define G1N_210001e0 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x10))
#define G1N_210001e4 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x14))
#define G1N_210001e8 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x18))
#define G1N_210001ec ((unsigned long)(g1_net_ram_blk_210001d0 + 0x1c))
#define G1N_210001f4 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x24))
#define G1N_21000204 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x34))
#define G1N_2100020c ((unsigned long)(g1_net_ram_blk_210001d0 + 0x3c))
#define G1N_21000214 ((unsigned long)(g1_net_ram_blk_210001d0 + 0x44))
#define G1N_21000308 ((unsigned long)(g1_net_ram_blk_21000308 + 0x0))
#define G1N_21000344 ((unsigned long)(g1_net_ram_blk_21000340 + 0x4))
#define G1N_21000354 ((unsigned long)(g1_net_ram_blk_21000340 + 0x14))
#define G1N_21000400 ((unsigned long)(g1_net_ram_blk_21000400 + 0x0))
#define G1N_210004ac ((unsigned long)(g1_net_ram_blk_210004a8 + 0x4))
#define G1N_210004b0 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x8))
#define G1N_210004b4 ((unsigned long)(g1_net_ram_blk_210004a8 + 0xc))
#define G1N_210004c8 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x20))
#define G1N_210004d0 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x28))
#define G1N_210004d8 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x30))
#define G1N_210004dc ((unsigned long)(g1_net_ram_blk_210004a8 + 0x34))
#define G1N_210004e0 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x38))
#define G1N_210004e8 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x40))
#define G1N_210004f0 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x48))
#define G1N_210004f8 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x50))
#define G1N_21000500 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x58))
#define G1N_21000508 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x60))
#define G1N_21000510 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x68))
#define G1N_21000518 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x70))
#define G1N_21000520 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x78))
#define G1N_21000528 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x80))
#define G1N_2100052c ((unsigned long)(g1_net_ram_blk_210004a8 + 0x84))
#define G1N_21000530 ((unsigned long)(g1_net_ram_blk_210004a8 + 0x88))
#define G1N_21000574 ((unsigned long)(g1_net_ram_blk_21000570 + 0x4))
#define G1N_2100057c ((unsigned long)(g1_net_ram_blk_21000570 + 0xc))
#define G1N_21000580 ((unsigned long)(g1_net_ram_blk_21000570 + 0x10))
#define G1N_210005ec ((unsigned long)(g1_net_ram_blk_210005e8 + 0x4))
#define G1N_2100065c ((unsigned long)(g1_net_ram_blk_21000658 + 0x4))
#define G1N_21000684 ((unsigned long)(g1_net_ram_blk_21000680 + 0x4))
#define G1N_2100068c ((unsigned long)(g1_net_ram_blk_21000680 + 0xc))
#define G1N_210006a8 ((unsigned long)(g1_net_ram_blk_21000680 + 0x28))
#define G1N_21000718 ((unsigned long)(g1_net_ram_blk_21000718 + 0x0))
#define G1N_2100071c ((unsigned long)(g1_net_ram_blk_21000718 + 0x4))
#define G1N_21000750 ((unsigned long)(g1_net_ram_blk_21000750 + 0x0))
#define G1N_210008cc ((unsigned long)(g1_net_ram_blk_210008c8 + 0x4))
#define G1N_210009fc ((unsigned long)(g1_net_ram_blk_210009f8 + 0x4))
#define G1N_21000a30 ((unsigned long)(g1_net_ram_blk_21000a30 + 0x0))
#define G1N_21000a40 ((unsigned long)(g1_net_ram_blk_21000a30 + 0x10))
#define G1N_21000a58 ((unsigned long)(g1_net_ram_blk_21000a30 + 0x28))
#define G1N_21000a60 ((unsigned long)(g1_net_ram_blk_21000a30 + 0x30))
#define G1N_21000a64 ((unsigned long)(g1_net_ram_blk_21000a30 + 0x34))
#define G1N_21000a68 ((unsigned long)(g1_net_ram_blk_21000a30 + 0x38))
#define G1N_21000a6c ((unsigned long)(g1_net_ram_blk_21000a30 + 0x3c))
#define G1N_21000b70 ((unsigned long)(g1_net_ram_blk_21000b70 + 0x0))
#define G1N_21000b78 ((unsigned long)(g1_net_ram_blk_21000b70 + 0x8))
#define G1N_21000b7c ((unsigned long)(g1_net_ram_blk_21000b70 + 0xc))
#define G1N_21000ba8 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x0))
#define G1N_21000bac ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x4))
#define G1N_21000bb0 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x8))
#define G1N_21000bb4 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0xc))
#define G1N_21000bb8 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x10))
#define G1N_21000bbc ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x14))
#define G1N_21000bc0 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x18))
#define G1N_21000bc4 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x1c))
#define G1N_21000bc8 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x20))
#define G1N_21000bc9 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x21))
#define G1N_21000be4 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x3c))
#define G1N_21000be8 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x40))
#define G1N_21000bec ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x44))
#define G1N_21000bf0 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x48))
#define G1N_21000bf4 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x4c))
#define G1N_21000bf8 ((unsigned long)(g1_net_ram_blk_21000ba8 + 0x50))
#define G1N_21000c2a ((unsigned long)(g1_net_ram_blk_21000c28 + 0x2))
#define G1N_21000c2c ((unsigned long)(g1_net_ram_blk_21000c28 + 0x4))
#define G1N_21000c2e ((unsigned long)(g1_net_ram_blk_21000c28 + 0x6))
#define G1N_21000c30 ((unsigned long)(g1_net_ram_blk_21000c28 + 0x8))
#define G1N_21000c34 ((unsigned long)(g1_net_ram_blk_21000c28 + 0xc))
#define G1N_21000c48 ((unsigned long)(g1_net_ram_blk_21000c28 + 0x20))
#define G1N_21000c6c ((unsigned long)(g1_net_ram_blk_21000c68 + 0x4))
#define G1N_21000c90 ((unsigned long)(g1_net_ram_blk_21000c90 + 0x0))
#define G1N_21000cc4 ((unsigned long)(g1_net_ram_blk_21000cc0 + 0x4))
#define G1N_21000cd0 ((unsigned long)(g1_net_ram_blk_21000cc0 + 0x10))
#define G1N_21000cfc ((unsigned long)(g1_net_ram_blk_21000cf8 + 0x4))
#define G1N_21000d18 ((unsigned long)(g1_net_ram_blk_21000cf8 + 0x20))
#define G1N_21000d1a ((unsigned long)(g1_net_ram_blk_21000cf8 + 0x22))
#define G1N_21000db0 ((unsigned long)(g1_net_ram_blk_21000db0 + 0x0))
#define G1N_21000ea6 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x6))
#define G1N_21000ea7 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x7))
#define G1N_21000ea8 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x8))
#define G1N_21000eac ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xc))
#define G1N_21000eae ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xe))
#define G1N_21000ec8 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x28))
#define G1N_21000ee0 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x40))
#define G1N_21000ef2 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x52))
#define G1N_21000ef4 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x54))
#define G1N_21000ef8 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x58))
#define G1N_21000efc ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x5c))
#define G1N_21000f00 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x60))
#define G1N_21000f04 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x64))
#define G1N_21000f14 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x74))
#define G1N_21000f20 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x80))
#define G1N_21000f24 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0x84))
#define G1N_21000f41 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xa1))
#define G1N_21000f45 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xa5))
#define G1N_21000f54 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xb4))
#define G1N_21000f58 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xb8))
#define G1N_21000f5c ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xbc))
#define G1N_21000f60 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xc0))
#define G1N_21000f64 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xc4))
#define G1N_21000f66 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xc6))
#define G1N_21000f68 ((unsigned long)(g1_net_ram_blk_21000ea0 + 0xc8))
#define G1N_21000f90 ((unsigned long)(g1_net_ram_blk_21000f90 + 0x0))
#define G1N_21000fc6 ((unsigned long)(g1_net_ram_blk_21000fc0 + 0x6))
#define G1N_21000fd6 ((unsigned long)(g1_net_ram_blk_21000fc0 + 0x16))
#define G1N_21000fec ((unsigned long)(g1_net_ram_blk_21000fc0 + 0x2c))
#define G1N_21001008 ((unsigned long)(g1_net_ram_blk_21000fc0 + 0x48))
#define G1N_21001014 ((unsigned long)(g1_net_ram_blk_21000fc0 + 0x54))
#define G1N_21001019 ((unsigned long)(g1_net_ram_blk_21000fc0 + 0x59))
#define G1N_21001048 ((unsigned long)(g1_net_ram_blk_21001048 + 0x0))
#define G1N_2100104a ((unsigned long)(g1_net_ram_blk_21001048 + 0x2))
#define G1N_2100104c ((unsigned long)(g1_net_ram_blk_21001048 + 0x4))
#define G1N_21001058 ((unsigned long)(g1_net_ram_blk_21001048 + 0x10))
#define G1N_2100109c ((unsigned long)(g1_net_ram_blk_21001098 + 0x4))
#define G1N_210010a0 ((unsigned long)(g1_net_ram_blk_21001098 + 0x8))
#define G1N_210010f0 ((unsigned long)(g1_net_ram_blk_210010f0 + 0x0))
#define G1N_2100111c ((unsigned long)(g1_net_ram_blk_21001118 + 0x4))
#define G1N_2100111d ((unsigned long)(g1_net_ram_blk_21001118 + 0x5))
#define G1N_21001120 ((unsigned long)(g1_net_ram_blk_21001118 + 0x8))
#define G1N_21001124 ((unsigned long)(g1_net_ram_blk_21001118 + 0xc))
#define G1N_21001128 ((unsigned long)(g1_net_ram_blk_21001118 + 0x10))
#define G1N_2100113c ((unsigned long)(g1_net_ram_blk_21001118 + 0x24))
#define G1N_21001140 ((unsigned long)(g1_net_ram_blk_21001118 + 0x28))
#define G1N_21001208 ((unsigned long)(g1_net_ram_blk_21001208 + 0x0))
#define G1N_21001225 ((unsigned long)(g1_net_ram_blk_21001208 + 0x1d))
#define G1N_21001230 ((unsigned long)(g1_net_ram_blk_21001208 + 0x28))
#define G1N_2100144a ((unsigned long)(g1_net_ram_blk_21001448 + 0x2))
#define G1N_21001498 ((unsigned long)(g1_net_ram_blk_21001498 + 0x0))
#define G1N_210014a8 ((unsigned long)(g1_net_ram_blk_21001498 + 0x10))
#define G1N_210014d8 ((unsigned long)(g1_net_ram_blk_210014d8 + 0x0))
#define G1N_210014dc ((unsigned long)(g1_net_ram_blk_210014d8 + 0x4))
#define G1N_210014e4 ((unsigned long)(g1_net_ram_blk_210014d8 + 0xc))
#define G1N_210015f0 ((unsigned long)(g1_net_ram_blk_210015f0 + 0x0))
#define G1N_210015f7 ((unsigned long)(g1_net_ram_blk_210015f0 + 0x7))
#define G1N_21001609 ((unsigned long)(g1_net_ram_blk_210015f0 + 0x19))
#define G1N_2100160a ((unsigned long)(g1_net_ram_blk_210015f0 + 0x1a))
#define G1N_21001614 ((unsigned long)(g1_net_ram_blk_210015f0 + 0x24))
#define G1N_2100163c ((unsigned long)(g1_net_ram_blk_21001638 + 0x4))
#define G1N_21001664 ((unsigned long)(g1_net_ram_blk_21001660 + 0x4))
#define G1N_21001670 ((unsigned long)(g1_net_ram_blk_21001660 + 0x10))
#define G1N_2100167c ((unsigned long)(g1_net_ram_blk_21001660 + 0x1c))
#define G1N_21001680 ((unsigned long)(g1_net_ram_blk_21001660 + 0x20))
#define G1N_210016b4 ((unsigned long)(g1_net_ram_blk_210016b0 + 0x4))
#define G1N_210016bc ((unsigned long)(g1_net_ram_blk_210016b0 + 0xc))
#define G1N_210016c0 ((unsigned long)(g1_net_ram_blk_210016b0 + 0x10))
#define G1N_210016c8 ((unsigned long)(g1_net_ram_blk_210016b0 + 0x18))
#define G1N_210016dc ((unsigned long)(g1_net_ram_blk_210016b0 + 0x2c))
#define G1N_210016e0 ((unsigned long)(g1_net_ram_blk_210016b0 + 0x30))
#define G1N_210016e4 ((unsigned long)(g1_net_ram_blk_210016b0 + 0x34))
#define G1N_210016e8 ((unsigned long)(g1_net_ram_blk_210016b0 + 0x38))
#define G1N_210016f0 ((unsigned long)(g1_net_ram_blk_210016b0 + 0x40))
#define G1N_21001740 ((unsigned long)(g1_net_ram_blk_21001740 + 0x0))
#define G1N_21001bca ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x2))
#define G1N_21001bcc ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x4))
#define G1N_21001bce ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x6))
#define G1N_21001bd0 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x8))
#define G1N_21001bd2 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0xa))
#define G1N_21001bd4 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0xc))
#define G1N_21001bd6 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0xe))
#define G1N_21001bdf ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x17))
#define G1N_21001bf7 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x2f))
#define G1N_21001bf8 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x30))
#define G1N_21001c08 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x40))
#define G1N_21001c18 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x50))
#define G1N_21001c1c ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x54))
#define G1N_21001c20 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x58))
#define G1N_21001c24 ((unsigned long)(g1_net_ram_blk_21001bc8 + 0x5c))
#define G1N_21001c88 ((unsigned long)(g1_net_ram_blk_21001c88 + 0x0))
#define G1N_21001ce8 ((unsigned long)(g1_net_ram_blk_21001ce8 + 0x0))
#define G1N_21001cf0 ((unsigned long)(g1_net_ram_blk_21001ce8 + 0x8))
#define G1N_21001cf8 ((unsigned long)(g1_net_ram_blk_21001ce8 + 0x10))
#define G1N_21001d00 ((unsigned long)(g1_net_ram_blk_21001ce8 + 0x18))
#define G1N_21002b60 ((unsigned long)(g1_net_ram_blk_21002b60 + 0x0))
#define G1N_21002b90 ((unsigned long)(g1_net_ram_blk_21002b90 + 0x0))
#define G1N_21004258 ((unsigned long)(g1_net_ram_blk_21004258 + 0x0))
#define G1N_210042f0 ((unsigned long)(g1_net_ram_blk_210042f0 + 0x0))
#define G1N_210045b0 ((unsigned long)(g1_net_ram_blk_210045b0 + 0x0))
#define G1N_210045c0 ((unsigned long)(g1_net_ram_blk_210045b0 + 0x10))
#define G1N_210045e4 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x4))
#define G1N_210045e8 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x8))
#define G1N_210045ec ((unsigned long)(g1_net_ram_blk_210045e0 + 0xc))
#define G1N_210045f0 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x10))
#define G1N_210045f4 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x14))
#define G1N_21004604 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x24))
#define G1N_21004610 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x30))
#define G1N_21004614 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x34))
#define G1N_21004618 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x38))
#define G1N_21004628 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x48))
#define G1N_2100462c ((unsigned long)(g1_net_ram_blk_210045e0 + 0x4c))
#define G1N_21004630 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x50))
#define G1N_21004638 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x58))
#define G1N_2100463c ((unsigned long)(g1_net_ram_blk_210045e0 + 0x5c))
#define G1N_21004640 ((unsigned long)(g1_net_ram_blk_210045e0 + 0x60))
#define G1N_21004670 ((unsigned long)(g1_net_ram_blk_21004670 + 0x0))
#define G1N_21004674 ((unsigned long)(g1_net_ram_blk_21004670 + 0x4))
#define G1N_21004690 ((unsigned long)(g1_net_ram_blk_21004670 + 0x20))
#define G1N_210047fc ((unsigned long)(g1_net_ram_blk_210047f8 + 0x4))
#define G1N_21004800 ((unsigned long)(g1_net_ram_blk_210047f8 + 0x8))
#define G1N_21004810 ((unsigned long)(g1_net_ram_blk_210047f8 + 0x18))
#define G1N_21004834 ((unsigned long)(g1_net_ram_blk_21004830 + 0x4))
#define G1N_21004964 ((unsigned long)(g1_net_ram_blk_21004960 + 0x4))
#define G1N_2100496c ((unsigned long)(g1_net_ram_blk_21004960 + 0xc))
#define G1N_21004974 ((unsigned long)(g1_net_ram_blk_21004960 + 0x14))
#define G1N_21004988 ((unsigned long)(g1_net_ram_blk_21004960 + 0x28))
#define G1N_2100499c ((unsigned long)(g1_net_ram_blk_21004960 + 0x3c))
#define G1N_210049a0 ((unsigned long)(g1_net_ram_blk_21004960 + 0x40))
#define G1N_210049a4 ((unsigned long)(g1_net_ram_blk_21004960 + 0x44))
#define G1N_210049a8 ((unsigned long)(g1_net_ram_blk_21004960 + 0x48))
#define G1N_210049ac ((unsigned long)(g1_net_ram_blk_21004960 + 0x4c))
#define G1N_210049b0 ((unsigned long)(g1_net_ram_blk_21004960 + 0x50))
#define G1N_210049b4 ((unsigned long)(g1_net_ram_blk_21004960 + 0x54))
#define G1N_210049d4 ((unsigned long)(g1_net_ram_blk_21004960 + 0x74))
#define G1N_21004a34 ((unsigned long)(g1_net_ram_blk_21004a30 + 0x4))
#define G1N_21004a60 ((unsigned long)(g1_net_ram_blk_21004a60 + 0x0))
#define G1N_21004a8c ((unsigned long)(g1_net_ram_blk_21004a88 + 0x4))
#define G1N_21004a90 ((unsigned long)(g1_net_ram_blk_21004a88 + 0x8))
#define G1N_21004a94 ((unsigned long)(g1_net_ram_blk_21004a88 + 0xc))
#define G1N_21004a9c ((unsigned long)(g1_net_ram_blk_21004a88 + 0x14))
#define G1N_21004aec ((unsigned long)(g1_net_ram_blk_21004ae8 + 0x4))
#define G1N_21004af8 ((unsigned long)(g1_net_ram_blk_21004ae8 + 0x10))
#define G1N_21004b04 ((unsigned long)(g1_net_ram_blk_21004ae8 + 0x1c))
#define G1N_21004b08 ((unsigned long)(g1_net_ram_blk_21004ae8 + 0x20))
#define G1N_21004b30 ((unsigned long)(g1_net_ram_blk_21004b30 + 0x0))
#define G1N_21004b48 ((unsigned long)(g1_net_ram_blk_21004b30 + 0x18))
#define G1N_21004b4c ((unsigned long)(g1_net_ram_blk_21004b30 + 0x1c))
#define G1N_21004b68 ((unsigned long)(g1_net_ram_blk_21004b30 + 0x38))
#define G1N_21004b6c ((unsigned long)(g1_net_ram_blk_21004b30 + 0x3c))
#define G1N_21004b7c ((unsigned long)(g1_net_ram_blk_21004b30 + 0x4c))
#define G1N_21004b9c ((unsigned long)(g1_net_ram_blk_21004b30 + 0x6c))
#define G1N_21004b9d ((unsigned long)(g1_net_ram_blk_21004b30 + 0x6d))
#define G1N_21004b9e ((unsigned long)(g1_net_ram_blk_21004b30 + 0x6e))
#define G1N_21004b9f ((unsigned long)(g1_net_ram_blk_21004b30 + 0x6f))
#define G1N_21004c9b ((unsigned long)(g1_net_ram_blk_21004c98 + 0x3))
#define G1N_21004c9c ((unsigned long)(g1_net_ram_blk_21004c98 + 0x4))
#define G1N_21004c9d ((unsigned long)(g1_net_ram_blk_21004c98 + 0x5))
#define G1N_21004c9e ((unsigned long)(g1_net_ram_blk_21004c98 + 0x6))
#define G1N_21004c9f ((unsigned long)(g1_net_ram_blk_21004c98 + 0x7))
#define G1N_21004ca0 ((unsigned long)(g1_net_ram_blk_21004c98 + 0x8))
#define G1N_21004ca1 ((unsigned long)(g1_net_ram_blk_21004c98 + 0x9))
#define G1N_21004da1 ((unsigned long)(g1_net_ram_blk_21004da0 + 0x1))
#define G1N_21004ea1 ((unsigned long)(g1_net_ram_blk_21004ea0 + 0x1))
#define G1N_21004fa1 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x1))
#define G1N_21004fa2 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x2))
#define G1N_21004fa3 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x3))
#define G1N_21004fa4 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x4))
#define G1N_21004fa5 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x5))
#define G1N_21004fa6 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x6))
#define G1N_21004fa7 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x7))
#define G1N_21004fa8 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x8))
#define G1N_21004fa9 ((unsigned long)(g1_net_ram_blk_21004fa0 + 0x9))
#define G1N_21004faa ((unsigned long)(g1_net_ram_blk_21004fa0 + 0xa))
#define G1N_21004fab ((unsigned long)(g1_net_ram_blk_21004fa0 + 0xb))
#define G1N_210051ae ((unsigned long)(g1_net_ram_blk_210051a8 + 0x6))
#define G1N_21005256 ((unsigned long)(g1_net_ram_blk_21005250 + 0x6))
#define G1N_21005a56 ((unsigned long)(g1_net_ram_blk_21005a50 + 0x6))
#define G1N_21006256 ((unsigned long)(g1_net_ram_blk_21006250 + 0x6))
#define G1N_2100625a ((unsigned long)(g1_net_ram_blk_21006250 + 0xa))
#define G1N_2100625e ((unsigned long)(g1_net_ram_blk_21006250 + 0xe))
#define G1N_2100635b ((unsigned long)(g1_net_ram_blk_21006358 + 0x3))
#define G1N_2100635d ((unsigned long)(g1_net_ram_blk_21006358 + 0x5))
#define G1N_21006458 ((unsigned long)(g1_net_ram_blk_21006458 + 0x0))
#define G1N_21006459 ((unsigned long)(g1_net_ram_blk_21006458 + 0x1))
#define G1N_2100645a ((unsigned long)(g1_net_ram_blk_21006458 + 0x2))
#define G1N_2100645b ((unsigned long)(g1_net_ram_blk_21006458 + 0x3))
#define G1N_2100645c ((unsigned long)(g1_net_ram_blk_21006458 + 0x4))
#define G1N_2100645d ((unsigned long)(g1_net_ram_blk_21006458 + 0x5))
#define G1N_2100645e ((unsigned long)(g1_net_ram_blk_21006458 + 0x6))
#define G1N_2100645f ((unsigned long)(g1_net_ram_blk_21006458 + 0x7))
#define G1N_21006460 ((unsigned long)(g1_net_ram_blk_21006458 + 0x8))
#define G1N_21006461 ((unsigned long)(g1_net_ram_blk_21006458 + 0x9))
#define G1N_21007d80 ((unsigned long)(g1_net_ram_blk_21007d80 + 0x0))
#define G1N_21008a00 ((unsigned long)(g1_net_ram_blk_21008a00 + 0x0))
#else
#define G1N_21000000 0x21000000ul
#define G1N_21000008 0x21000008ul
#define G1N_21000010 0x21000010ul
#define G1N_21000018 0x21000018ul
#define G1N_2100001c 0x2100001cul
#define G1N_21000020 0x21000020ul
#define G1N_21000028 0x21000028ul
#define G1N_2100003c 0x2100003cul
#define G1N_21000040 0x21000040ul
#define G1N_21000044 0x21000044ul
#define G1N_21000048 0x21000048ul
#define G1N_2100004c 0x2100004cul
#define G1N_21000050 0x21000050ul
#define G1N_21000054 0x21000054ul
#define G1N_21000058 0x21000058ul
#define G1N_2100005c 0x2100005cul
#define G1N_21000078 0x21000078ul
#define G1N_21000124 0x21000124ul
#define G1N_210001d0 0x210001d0ul
#define G1N_210001d4 0x210001d4ul
#define G1N_210001dc 0x210001dcul
#define G1N_210001e0 0x210001e0ul
#define G1N_210001e4 0x210001e4ul
#define G1N_210001e8 0x210001e8ul
#define G1N_210001ec 0x210001ecul
#define G1N_210001f4 0x210001f4ul
#define G1N_21000204 0x21000204ul
#define G1N_2100020c 0x2100020cul
#define G1N_21000214 0x21000214ul
#define G1N_21000308 0x21000308ul
#define G1N_21000344 0x21000344ul
#define G1N_21000354 0x21000354ul
#define G1N_21000400 0x21000400ul
#define G1N_210004ac 0x210004acul
#define G1N_210004b0 0x210004b0ul
#define G1N_210004b4 0x210004b4ul
#define G1N_210004c8 0x210004c8ul
#define G1N_210004d0 0x210004d0ul
#define G1N_210004d8 0x210004d8ul
#define G1N_210004dc 0x210004dcul
#define G1N_210004e0 0x210004e0ul
#define G1N_210004e8 0x210004e8ul
#define G1N_210004f0 0x210004f0ul
#define G1N_210004f8 0x210004f8ul
#define G1N_21000500 0x21000500ul
#define G1N_21000508 0x21000508ul
#define G1N_21000510 0x21000510ul
#define G1N_21000518 0x21000518ul
#define G1N_21000520 0x21000520ul
#define G1N_21000528 0x21000528ul
#define G1N_2100052c 0x2100052cul
#define G1N_21000530 0x21000530ul
#define G1N_21000574 0x21000574ul
#define G1N_2100057c 0x2100057cul
#define G1N_21000580 0x21000580ul
#define G1N_210005ec 0x210005ecul
#define G1N_2100065c 0x2100065cul
#define G1N_21000684 0x21000684ul
#define G1N_2100068c 0x2100068cul
#define G1N_210006a8 0x210006a8ul
#define G1N_21000718 0x21000718ul
#define G1N_2100071c 0x2100071cul
#define G1N_21000750 0x21000750ul
#define G1N_210008cc 0x210008ccul
#define G1N_210009fc 0x210009fcul
#define G1N_21000a30 0x21000a30ul
#define G1N_21000a40 0x21000a40ul
#define G1N_21000a58 0x21000a58ul
#define G1N_21000a60 0x21000a60ul
#define G1N_21000a64 0x21000a64ul
#define G1N_21000a68 0x21000a68ul
#define G1N_21000a6c 0x21000a6cul
#define G1N_21000b70 0x21000b70ul
#define G1N_21000b78 0x21000b78ul
#define G1N_21000b7c 0x21000b7cul
#define G1N_21000ba8 0x21000ba8ul
#define G1N_21000bac 0x21000bacul
#define G1N_21000bb0 0x21000bb0ul
#define G1N_21000bb4 0x21000bb4ul
#define G1N_21000bb8 0x21000bb8ul
#define G1N_21000bbc 0x21000bbcul
#define G1N_21000bc0 0x21000bc0ul
#define G1N_21000bc4 0x21000bc4ul
#define G1N_21000bc8 0x21000bc8ul
#define G1N_21000bc9 0x21000bc9ul
#define G1N_21000be4 0x21000be4ul
#define G1N_21000be8 0x21000be8ul
#define G1N_21000bec 0x21000becul
#define G1N_21000bf0 0x21000bf0ul
#define G1N_21000bf4 0x21000bf4ul
#define G1N_21000bf8 0x21000bf8ul
#define G1N_21000c2a 0x21000c2aul
#define G1N_21000c2c 0x21000c2cul
#define G1N_21000c2e 0x21000c2eul
#define G1N_21000c30 0x21000c30ul
#define G1N_21000c34 0x21000c34ul
#define G1N_21000c48 0x21000c48ul
#define G1N_21000c6c 0x21000c6cul
#define G1N_21000c90 0x21000c90ul
#define G1N_21000cc4 0x21000cc4ul
#define G1N_21000cd0 0x21000cd0ul
#define G1N_21000cfc 0x21000cfcul
#define G1N_21000d18 0x21000d18ul
#define G1N_21000d1a 0x21000d1aul
#define G1N_21000db0 0x21000db0ul
#define G1N_21000ea6 0x21000ea6ul
#define G1N_21000ea7 0x21000ea7ul
#define G1N_21000ea8 0x21000ea8ul
#define G1N_21000eac 0x21000eacul
#define G1N_21000eae 0x21000eaeul
#define G1N_21000ec8 0x21000ec8ul
#define G1N_21000ee0 0x21000ee0ul
#define G1N_21000ef2 0x21000ef2ul
#define G1N_21000ef4 0x21000ef4ul
#define G1N_21000ef8 0x21000ef8ul
#define G1N_21000efc 0x21000efcul
#define G1N_21000f00 0x21000f00ul
#define G1N_21000f04 0x21000f04ul
#define G1N_21000f14 0x21000f14ul
#define G1N_21000f20 0x21000f20ul
#define G1N_21000f24 0x21000f24ul
#define G1N_21000f41 0x21000f41ul
#define G1N_21000f45 0x21000f45ul
#define G1N_21000f54 0x21000f54ul
#define G1N_21000f58 0x21000f58ul
#define G1N_21000f5c 0x21000f5cul
#define G1N_21000f60 0x21000f60ul
#define G1N_21000f64 0x21000f64ul
#define G1N_21000f66 0x21000f66ul
#define G1N_21000f68 0x21000f68ul
#define G1N_21000f90 0x21000f90ul
#define G1N_21000fc6 0x21000fc6ul
#define G1N_21000fd6 0x21000fd6ul
#define G1N_21000fec 0x21000fecul
#define G1N_21001008 0x21001008ul
#define G1N_21001014 0x21001014ul
#define G1N_21001019 0x21001019ul
#define G1N_21001048 0x21001048ul
#define G1N_2100104a 0x2100104aul
#define G1N_2100104c 0x2100104cul
#define G1N_21001058 0x21001058ul
#define G1N_2100109c 0x2100109cul
#define G1N_210010a0 0x210010a0ul
#define G1N_210010f0 0x210010f0ul
#define G1N_2100111c 0x2100111cul
#define G1N_2100111d 0x2100111dul
#define G1N_21001120 0x21001120ul
#define G1N_21001124 0x21001124ul
#define G1N_21001128 0x21001128ul
#define G1N_2100113c 0x2100113cul
#define G1N_21001140 0x21001140ul
#define G1N_21001208 0x21001208ul
#define G1N_21001225 0x21001225ul
#define G1N_21001230 0x21001230ul
#define G1N_2100144a 0x2100144aul
#define G1N_21001498 0x21001498ul
#define G1N_210014a8 0x210014a8ul
#define G1N_210014d8 0x210014d8ul
#define G1N_210014dc 0x210014dcul
#define G1N_210014e4 0x210014e4ul
#define G1N_210015f0 0x210015f0ul
#define G1N_210015f7 0x210015f7ul
#define G1N_21001609 0x21001609ul
#define G1N_2100160a 0x2100160aul
#define G1N_21001614 0x21001614ul
#define G1N_2100163c 0x2100163cul
#define G1N_21001664 0x21001664ul
#define G1N_21001670 0x21001670ul
#define G1N_2100167c 0x2100167cul
#define G1N_21001680 0x21001680ul
#define G1N_210016b4 0x210016b4ul
#define G1N_210016bc 0x210016bcul
#define G1N_210016c0 0x210016c0ul
#define G1N_210016c8 0x210016c8ul
#define G1N_210016dc 0x210016dcul
#define G1N_210016e0 0x210016e0ul
#define G1N_210016e4 0x210016e4ul
#define G1N_210016e8 0x210016e8ul
#define G1N_210016f0 0x210016f0ul
#define G1N_21001740 0x21001740ul
#define G1N_21001bca 0x21001bcaul
#define G1N_21001bcc 0x21001bccul
#define G1N_21001bce 0x21001bceul
#define G1N_21001bd0 0x21001bd0ul
#define G1N_21001bd2 0x21001bd2ul
#define G1N_21001bd4 0x21001bd4ul
#define G1N_21001bd6 0x21001bd6ul
#define G1N_21001bdf 0x21001bdful
#define G1N_21001bf7 0x21001bf7ul
#define G1N_21001bf8 0x21001bf8ul
#define G1N_21001c08 0x21001c08ul
#define G1N_21001c18 0x21001c18ul
#define G1N_21001c1c 0x21001c1cul
#define G1N_21001c20 0x21001c20ul
#define G1N_21001c24 0x21001c24ul
#define G1N_21001c88 0x21001c88ul
#define G1N_21001ce8 0x21001ce8ul
#define G1N_21001cf0 0x21001cf0ul
#define G1N_21001cf8 0x21001cf8ul
#define G1N_21001d00 0x21001d00ul
#define G1N_21002b60 0x21002b60ul
#define G1N_21002b90 0x21002b90ul
#define G1N_21004258 0x21004258ul
#define G1N_210042f0 0x210042f0ul
#define G1N_210045b0 0x210045b0ul
#define G1N_210045c0 0x210045c0ul
#define G1N_210045e4 0x210045e4ul
#define G1N_210045e8 0x210045e8ul
#define G1N_210045ec 0x210045ecul
#define G1N_210045f0 0x210045f0ul
#define G1N_210045f4 0x210045f4ul
#define G1N_21004604 0x21004604ul
#define G1N_21004610 0x21004610ul
#define G1N_21004614 0x21004614ul
#define G1N_21004618 0x21004618ul
#define G1N_21004628 0x21004628ul
#define G1N_2100462c 0x2100462cul
#define G1N_21004630 0x21004630ul
#define G1N_21004638 0x21004638ul
#define G1N_2100463c 0x2100463cul
#define G1N_21004640 0x21004640ul
#define G1N_21004670 0x21004670ul
#define G1N_21004674 0x21004674ul
#define G1N_21004690 0x21004690ul
#define G1N_210047fc 0x210047fcul
#define G1N_21004800 0x21004800ul
#define G1N_21004810 0x21004810ul
#define G1N_21004834 0x21004834ul
#define G1N_21004964 0x21004964ul
#define G1N_2100496c 0x2100496cul
#define G1N_21004974 0x21004974ul
#define G1N_21004988 0x21004988ul
#define G1N_2100499c 0x2100499cul
#define G1N_210049a0 0x210049a0ul
#define G1N_210049a4 0x210049a4ul
#define G1N_210049a8 0x210049a8ul
#define G1N_210049ac 0x210049acul
#define G1N_210049b0 0x210049b0ul
#define G1N_210049b4 0x210049b4ul
#define G1N_210049d4 0x210049d4ul
#define G1N_21004a34 0x21004a34ul
#define G1N_21004a60 0x21004a60ul
#define G1N_21004a8c 0x21004a8cul
#define G1N_21004a90 0x21004a90ul
#define G1N_21004a94 0x21004a94ul
#define G1N_21004a9c 0x21004a9cul
#define G1N_21004aec 0x21004aecul
#define G1N_21004af8 0x21004af8ul
#define G1N_21004b04 0x21004b04ul
#define G1N_21004b08 0x21004b08ul
#define G1N_21004b30 0x21004b30ul
#define G1N_21004b48 0x21004b48ul
#define G1N_21004b4c 0x21004b4cul
#define G1N_21004b68 0x21004b68ul
#define G1N_21004b6c 0x21004b6cul
#define G1N_21004b7c 0x21004b7cul
#define G1N_21004b9c 0x21004b9cul
#define G1N_21004b9d 0x21004b9dul
#define G1N_21004b9e 0x21004b9eul
#define G1N_21004b9f 0x21004b9ful
#define G1N_21004c9b 0x21004c9bul
#define G1N_21004c9c 0x21004c9cul
#define G1N_21004c9d 0x21004c9dul
#define G1N_21004c9e 0x21004c9eul
#define G1N_21004c9f 0x21004c9ful
#define G1N_21004ca0 0x21004ca0ul
#define G1N_21004ca1 0x21004ca1ul
#define G1N_21004da1 0x21004da1ul
#define G1N_21004ea1 0x21004ea1ul
#define G1N_21004fa1 0x21004fa1ul
#define G1N_21004fa2 0x21004fa2ul
#define G1N_21004fa3 0x21004fa3ul
#define G1N_21004fa4 0x21004fa4ul
#define G1N_21004fa5 0x21004fa5ul
#define G1N_21004fa6 0x21004fa6ul
#define G1N_21004fa7 0x21004fa7ul
#define G1N_21004fa8 0x21004fa8ul
#define G1N_21004fa9 0x21004fa9ul
#define G1N_21004faa 0x21004faaul
#define G1N_21004fab 0x21004fabul
#define G1N_210051ae 0x210051aeul
#define G1N_21005256 0x21005256ul
#define G1N_21005a56 0x21005a56ul
#define G1N_21006256 0x21006256ul
#define G1N_2100625a 0x2100625aul
#define G1N_2100625e 0x2100625eul
#define G1N_2100635b 0x2100635bul
#define G1N_2100635d 0x2100635dul
#define G1N_21006458 0x21006458ul
#define G1N_21006459 0x21006459ul
#define G1N_2100645a 0x2100645aul
#define G1N_2100645b 0x2100645bul
#define G1N_2100645c 0x2100645cul
#define G1N_2100645d 0x2100645dul
#define G1N_2100645e 0x2100645eul
#define G1N_2100645f 0x2100645ful
#define G1N_21006460 0x21006460ul
#define G1N_21006461 0x21006461ul
#define G1N_21007d80 0x21007d80ul
#define G1N_21008a00 0x21008a00ul
#endif

#endif /* G1_NET_RAM_RELOC_H_ */
